from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
)
from django.urls import include, path, reverse_lazy

from . import views
from .encryption_views import (
    EncryptionSetupPageView,
    EncryptionSetupView,
    EncryptionStatusView,
    MembershipEncryptionKeyDeleteView,
    MembershipEncryptionKeyListView,
    RecoveryPageView,
    RecoveryTriggerView,
    UserEncryptionKeyView,
)

app_name = "accounts"

urlpatterns = [
    path(
        "account/",
        include(
            [
                path(
                    "login",
                    LoginView.as_view(template_name="login.html"),
                    name="login",
                ),
                path("signup", views.SignupView.as_view(), name="signup"),
                path(
                    "verify-email/<str:token>",
                    views.EmailVerificationView.as_view(),
                    name="email-verify",
                ),
                path("logout", LogoutView.as_view(), name="logout"),
                path(
                    "password-reset/",
                    include(
                        [
                            path(
                                "",
                                views.VerifiedPasswordResetView.as_view(
                                    success_url=reverse_lazy(
                                        "accounts:password-reset-done"
                                    )
                                ),
                                name="password-reset",
                            ),
                            path(
                                "done",
                                PasswordResetDoneView.as_view(),
                                name="password-reset-done",
                            ),
                            path(
                                "<uidb64>/<token>",
                                PasswordResetConfirmView.as_view(
                                    success_url=reverse_lazy(
                                        "accounts:password-reset-complete"
                                    )
                                ),
                                name="password-reset-confirm",
                            ),
                            path(
                                "complete",
                                PasswordResetCompleteView.as_view(),
                                name="password-reset-complete",
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
    path(
        "organizations/",
        include(
            [
                path("", views.OrganizationListView.as_view(), name="org-list"),
            ]
        ),
    ),
    path(
        "org/<slug:org_slug>/",
        include(
            [
                path(
                    "",
                    views.OrganizationHomeView.as_view(),
                    name="org-home",
                ),
                path(
                    "encryption/",
                    include(
                        [
                            path(
                                "",
                                EncryptionStatusView.as_view(),
                                name="encryption-status",
                            ),
                            path(
                                "setup/",
                                EncryptionSetupView.as_view(),
                                name="encryption-setup",
                            ),
                            path(
                                "setup",
                                EncryptionSetupPageView.as_view(),
                                name="encryption-setup-page",
                            ),
                            path(
                                "user-key/",
                                UserEncryptionKeyView.as_view(),
                                name="user-encryption-key",
                            ),
                            path(
                                "membership-key/",
                                MembershipEncryptionKeyListView.as_view(),
                                name="membership-encryption-key-list",
                            ),
                            path(
                                "membership-key/<int:membership_pk>/delete",
                                MembershipEncryptionKeyDeleteView.as_view(),
                                name="membership-encryption-key-delete",
                            ),
                            path(
                                "recover",
                                RecoveryTriggerView.as_view(),
                                name="encryption-recover",
                            ),
                            path(
                                "recover-page",
                                RecoveryPageView.as_view(),
                                name="encryption-recover-page",
                            ),
                        ]
                    ),
                ),
                path(
                    "settings/",
                    include(
                        [
                            path(
                                "",
                                views.OrganizationDetailView.as_view(),
                                name="org-detail",
                            ),
                            path(
                                "edit",
                                views.OrganizationUpdateView.as_view(),
                                name="org-update",
                            ),
                            path(
                                "delete",
                                views.OrganizationDeleteView.as_view(),
                                name="org-delete",
                            ),
                            path(
                                "members/",
                                include(
                                    [
                                        path(
                                            "new",
                                            views.MembershipCreateView.as_view(),
                                            name="member-create",
                                        ),
                                        path(
                                            "<int:member_pk>/delete",
                                            views.MembershipDeleteView.as_view(),
                                            name="member-delete",
                                        ),
                                        path(
                                            "<int:member_pk>/edit",
                                            views.MembershipUpdateView.as_view(),
                                            name="member-update",
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
]
