# Generated by Django 6.1 on 2026-09-01 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kms", "0003_certificate"),
        ("mta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingmessage",
            name="tls_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="Certificate the sending MTA presented, when one was offered.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_messages",
                to="kms.certificate",
            ),
        ),
        migrations.AddField(
            model_name="incomingmessage",
            name="tls_cipher",
            field=models.TextField(
                blank=True,
                help_text="Negotiated TLS cipher suite.",
                verbose_name="TLS cipher",
            ),
        ),
        migrations.AddField(
            model_name="incomingmessage",
            name="tls_version",
            field=models.TextField(
                blank=True,
                help_text="Negotiated TLS protocol version, for example TLSv1.3.",
                verbose_name="TLS version",
            ),
        ),
    ]
