# Generated by Django 6.1 on 2026-08-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mta", "0002_webhookencryptionkey_sealedfilekey"),
    ]

    operations = [
        migrations.AddField(
            model_name="sealedfilekey",
            name="webhook_key_id",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Fingerprint of the webhook encryption key used for sealing.",
                max_length=16,
                verbose_name="webhook key ID",
            ),
        ),
    ]
