# Generated by Django 6.1 on 2026-09-01 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kms", "0003_certificate"),
        ("mta", "0002_incomingmessage_tls_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingmessage",
            name="tls_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="Certificate the sending MTA presented, when one was offered.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_messages",
                to="kms.certificate",
            ),
        ),
    ]
