# Generated by Django 6.1.1 on 2026-09-09 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0008_remove_message_received_with_tls_and_more"),
        ("mta", "0003_webhookdelivery_timing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            "webhookdelivery",
            options={
                "ordering": ["started_at", "created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.RemoveField(
            model_name="incomingmessage",
            name="tls_certificate",
        ),
        migrations.RemoveField(
            model_name="incomingmessage",
            name="tls_cipher",
        ),
        migrations.RemoveField(
            model_name="incomingmessage",
            name="tls_version",
        ),
    ]
