# Generated by Django 6.1.1 on 2026-09-09 19:49

from django.db import migrations


def backfill_receptions(apps, schema_editor):
    """Record the reception transmission of every inbound message on file."""
    transmission_model = apps.get_model("message", "transmission")
    incoming_messages = apps.get_model("mta", "incomingmessage").objects.all()
    for message in incoming_messages:
        transmission_model.objects.create(
            message=message,
            status="received",
            code=250,
            output="250 OK",
            tls_mode=("starttls" if message.received_with_tls else "plaintext"),
            tls_version=message.tls_version,
            tls_cipher=message.tls_cipher,
            tls_certificate_id=message.tls_certificate_id,
            started_at=message.created_at,
            finished_at=message.created_at,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0008_alter_message_spam_action_transmission"),
        ("mta", "0003_webhookdelivery_timing"),
    ]

    operations = [
        migrations.RunPython(backfill_receptions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="incomingmessage",
            name="tls_certificate",
        ),
        migrations.RemoveField(
            model_name="incomingmessage",
            name="tls_cipher",
        ),
        migrations.RemoveField(
            model_name="incomingmessage",
            name="tls_version",
        ),
    ]
