scripts:
  - name: CSS watcher
    command: |
      pnpm ci
      pnpm run dev
  - name: Dev server
    command: |
      rm db.sqlite3 || true
      uv run --env-file .env manage.py migrate --noinput
      uv run --env-file .env manage.py loaddata fixtures/initial_data.yaml
      uv run --env-file .env manage.py runserver "localhost:$(python3 -c "import socket; s=socket.socket(); s.bind(('127.0.0.1',0)); print(s.getsockname()[1]); s.close()")"
  - name: Dump test data
    command: |
      uv run --env-file .env manage.py dumpdata auth accounts kms domains smtp \
        --format yaml --output fixtures/initial_data.yaml
    disabled: true
auto_open_in_browser: true
automation:
  auto_issue_session: true
