apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvcs.yaml
  - configmap.yaml
  - caddy.yaml
  - dns.yaml
  - web.yaml
  - mcp.yaml
  - mail.yaml
  - data.yaml
  - dozzle.yaml
configMapGenerator:
  - name: caddy-config
    files:
      - caddy/Caddyfile
  - name: dnsdist-config
    files:
      - dnsdist/dnsdist.conf
images:
  - name: ghcr.io/codingjoe/relay
    newTag: local
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: relay
