# Generated by Django 6.1rc1 on 2026-08-04 12:29

from django.db import migrations

import services.email.smtp.models


class Migration(migrations.Migration):
    dependencies = [
        ("smtp", "0002_suppressionentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppressionentry",
            name="address_hash",
            field=services.email.smtp.models.HashedEmailField(
                help_text="Salted SHA-256 of the lowercased email address.",
                verbose_name="address hash",
            ),
        ),
    ]
