# Generated by Django 6.0.6 on 2026-07-27 11:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("kms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingMessage",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "mail_from",
                    models.EmailField(
                        help_text="Envelope sender address (MAIL FROM).",
                        max_length=254,
                        verbose_name="mail from",
                    ),
                ),
                (
                    "rcpt_to",
                    models.TextField(
                        help_text="Envelope recipient address(es) (RCPT TO).",
                        verbose_name="rcpt to",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        blank=True,
                        help_text="RFC 5322 Subject header value.",
                        verbose_name="subject",
                    ),
                ),
                (
                    "message_id",
                    models.TextField(
                        blank=True,
                        help_text="RFC 5322 Message-ID header.",
                        verbose_name="message ID",
                    ),
                ),
                (
                    "raw_body",
                    models.FileField(
                        blank=True,
                        help_text="Raw RFC 822 message bytes.",
                        upload_to="messages/",
                        verbose_name="raw body",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the message was accepted.",
                        verbose_name="received at",
                    ),
                ),
                (
                    "received_with_tls",
                    models.BooleanField(
                        default=False,
                        help_text="Submission received over TLS.",
                        verbose_name="received with TLS",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receiving_domain",
                    models.CharField(
                        blank=True,
                        help_text="Domain part of the recipient address, e.g. app.acme.com.",
                        max_length=255,
                        verbose_name="receiving domain",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("webhook_sent", "webhook sent"),
                            ("webhook_failed", "webhook failed"),
                            ("dropped", "dropped"),
                        ],
                        default="received",
                        help_text="Ingress and webhook delivery lifecycle state.",
                        max_length=14,
                        verbose_name="status",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_messages",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="HTTPS endpoint to receive incoming-mail webhook deliveries.",
                        validators=[
                            django.core.validators.RegexValidator(
                                "^https://", "Webhook URL must use HTTPS."
                            )
                        ],
                        verbose_name="URL",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "address_pattern",
                    models.CharField(
                        help_text="Glob pattern for recipient addresses, e.g. *@app.acme.com or support@acme.com.",
                        max_length=255,
                        verbose_name="address pattern",
                    ),
                ),
                (
                    "mx_status",
                    models.CharField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="MX record verification result for the receiving domain.",
                        max_length=9,
                        verbose_name="MX status",
                    ),
                ),
                (
                    "mx_error",
                    models.TextField(
                        blank=True,
                        help_text="Failure detail if the MX record is incorrect.",
                        verbose_name="MX error",
                    ),
                ),
                (
                    "mx_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last MX check timestamp.",
                        null=True,
                        verbose_name="MX checked at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive webhooks receive no deliveries.",
                        verbose_name="active",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful webhook delivery.",
                        null=True,
                        verbose_name="last used",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.organization",
                    ),
                ),
                (
                    "signing_key",
                    models.ForeignKey(
                        help_text="Ed25519 keypair used to sign webhook payloads.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhooks",
                        to="kms.signingkey",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_test",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this was a test delivery.",
                        verbose_name="test",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "sent"), ("failed", "failed")],
                        help_text="Outcome of this webhook delivery attempt.",
                        max_length=7,
                        verbose_name="status",
                    ),
                ),
                (
                    "response_code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="HTTP status code returned by the webhook endpoint.",
                        null=True,
                        verbose_name="response code",
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        blank=True,
                        help_text="Truncated response body from the webhook endpoint.",
                        verbose_name="response body",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated incoming message, or null for a test delivery.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_deliveries",
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="mx.webhook",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="incomingmessage",
            index=models.Index(
                fields=["org", "status"], name="mx_incoming_org_id_9b09d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingmessage",
            index=models.Index(
                fields=["org", "received_at"], name="mx_incoming_org_id_2a4062_idx"
            ),
        ),
    ]
