# Generated by Django 6.0.6 on 2026-07-29 20:27

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("domains", "0001_initial"),
        ("kms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingMessage",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "mail_from",
                    models.EmailField(
                        help_text="Envelope sender address (MAIL FROM).",
                        max_length=254,
                        verbose_name="mail from",
                    ),
                ),
                (
                    "rcpt_to",
                    models.TextField(
                        help_text="Envelope recipient address(es) (RCPT TO).",
                        verbose_name="rcpt to",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        blank=True,
                        help_text="RFC 5322 Subject header value.",
                        verbose_name="subject",
                    ),
                ),
                (
                    "message_id",
                    models.TextField(
                        blank=True,
                        help_text="RFC 5322 Message-ID header.",
                        verbose_name="message ID",
                    ),
                ),
                (
                    "raw_body",
                    models.FileField(
                        blank=True,
                        help_text="Raw RFC 822 message bytes.",
                        upload_to="messages/",
                        verbose_name="raw body",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the message was accepted.",
                        verbose_name="received at",
                    ),
                ),
                (
                    "received_with_tls",
                    models.BooleanField(
                        default=False,
                        help_text="Submission received over TLS.",
                        verbose_name="received with TLS",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receiving_domain",
                    models.TextField(
                        blank=True,
                        help_text="Domain part of the recipient address, e.g. app.acme.com.",
                        verbose_name="receiving domain",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("received", "received"),
                            ("webhook_sent", "webhook sent"),
                            ("webhook_failed", "webhook failed"),
                            ("dropped", "dropped"),
                        ],
                        default="received",
                        help_text="Ingress and webhook delivery lifecycle state.",
                        verbose_name="status",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_messages",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="HTTPS endpoint to receive incoming-mail webhook deliveries.",
                        validators=[
                            django.core.validators.RegexValidator(
                                "^https://", "Webhook URL must use HTTPS."
                            )
                        ],
                        verbose_name="URL",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable label.",
                        verbose_name="name",
                    ),
                ),
                (
                    "address_pattern",
                    models.TextField(
                        help_text="Glob pattern for recipient addresses, e.g. *@app.acme.com or support@acme.com.",
                        verbose_name="address pattern",
                    ),
                ),
                (
                    "mx_status",
                    models.TextField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="MX record verification result for the receiving domain.",
                        verbose_name="MX status",
                    ),
                ),
                (
                    "mx_error",
                    models.TextField(
                        blank=True,
                        help_text="Failure detail if the MX record is incorrect.",
                        verbose_name="MX error",
                    ),
                ),
                (
                    "mx_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last MX check timestamp.",
                        null=True,
                        verbose_name="MX checked at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive webhooks receive no deliveries.",
                        verbose_name="active",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful webhook delivery.",
                        null=True,
                        verbose_name="last used",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.organization",
                    ),
                ),
                (
                    "signing_key",
                    models.ForeignKey(
                        help_text="Ed25519 keypair used to sign webhook payloads.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhooks",
                        to="kms.signingkey",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_test",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this was a test delivery.",
                        verbose_name="test",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("sent", "sent"), ("failed", "failed")],
                        help_text="Outcome of this webhook delivery attempt.",
                        verbose_name="status",
                    ),
                ),
                (
                    "response_code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="HTTP status code returned by the webhook endpoint.",
                        null=True,
                        verbose_name="response code",
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        blank=True,
                        help_text="Truncated response body from the webhook endpoint.",
                        verbose_name="response body",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated incoming message, or null for a test delivery.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_deliveries",
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="mx.webhook",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TlsReport",
            fields=[
                (
                    "incomingmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "reporting_org",
                    models.TextField(
                        blank=True,
                        help_text="Organization that generated the report.",
                        verbose_name="reporting organization",
                    ),
                ),
                (
                    "reporting_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email from the report metadata.",
                        max_length=254,
                        verbose_name="reporting email",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(
                        help_text="Unique report identifier.", verbose_name="report ID"
                    ),
                ),
                (
                    "begin_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the report period.",
                        null=True,
                        verbose_name="begin at",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the report period.",
                        null=True,
                        verbose_name="end at",
                    ),
                ),
                (
                    "successful_session_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total successful TLS sessions.",
                        verbose_name="successful session count",
                    ),
                ),
                (
                    "failed_session_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total failed TLS sessions.",
                        verbose_name="failed session count",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Domain the report covers.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tls_reports",
                        to="domains.domain",
                    ),
                ),
            ],
            bases=("mx.incomingmessage",),
        ),
        migrations.CreateModel(
            name="TlsFailure",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "policy_type",
                    models.TextField(
                        choices=[("sts", "STS"), ("tlsa", "TLSA")],
                        help_text="Policy that was applied.",
                        verbose_name="policy type",
                    ),
                ),
                (
                    "policy_domain",
                    models.TextField(
                        blank=True,
                        help_text="Domain the policy applies to.",
                        verbose_name="policy domain",
                    ),
                ),
                (
                    "result_type",
                    models.TextField(
                        choices=[
                            ("starttls-not-supported", "STARTTLS not supported"),
                            ("certificate-expired", "certificate expired"),
                            ("certificate-not-trusted", "certificate not trusted"),
                            ("certificate-name-mismatch", "certificate name mismatch"),
                            ("tls-version-invalid", "TLS version invalid"),
                            ("tlsa-invalid", "TLSA invalid"),
                            ("dane-required", "DANE required"),
                            ("sts-policy-invalid", "STS policy invalid"),
                            ("sts-webpki-invalid", "STS WebPKI invalid"),
                            ("other", "other"),
                        ],
                        help_text="TLS failure type.",
                        verbose_name="result type",
                    ),
                ),
                (
                    "sending_mta_ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address of the sending MTA.",
                        verbose_name="sending MTA IP address",
                    ),
                ),
                (
                    "receiving_mx_hostname",
                    models.TextField(
                        blank=True,
                        help_text="Hostname of the receiving MX.",
                        verbose_name="receiving MX hostname",
                    ),
                ),
                (
                    "receiving_mx_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the receiving MX.",
                        null=True,
                        verbose_name="receiving MX IP address",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of failed sessions with this configuration.",
                        verbose_name="count",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        help_text="Extra failure details from the report.",
                        verbose_name="additional info",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="mx.tlsreport",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="incomingmessage",
            index=models.Index(
                fields=["org", "status"], name="mx_incoming_org_id_9b09d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingmessage",
            index=models.Index(
                fields=["org", "received_at"], name="mx_incoming_org_id_2a4062_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tlsreport",
            index=models.Index(
                fields=["begin_at"], name="mx_tlsrepor_begin_a_6dd35d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tlsreport",
            constraint=models.UniqueConstraint(
                fields=("domain", "report_id"), name="unique_tls_report"
            ),
        ),
        migrations.AddIndex(
            model_name="tlsfailure",
            index=models.Index(
                fields=["report", "result_type"], name="mx_tlsfailu_report__bccc64_idx"
            ),
        ),
    ]
