# Generated by Django 6.1.1 on 2026-09-15 17:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("domains", "0001_initial"),
        ("kms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mail_from",
                    models.EmailField(
                        help_text="Envelope sender address (MAIL FROM).",
                        max_length=254,
                        verbose_name="mail from",
                    ),
                ),
                (
                    "rcpt_to",
                    models.TextField(
                        help_text="Envelope recipient address(es) (RCPT TO).",
                        verbose_name="rcpt to",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        blank=True,
                        help_text="Subject header value with RFC 2047 encoded-words decoded.",
                        verbose_name="subject",
                    ),
                ),
                (
                    "message_id",
                    models.TextField(
                        blank=True,
                        help_text="RFC 5322 Message-ID header.",
                        verbose_name="message ID",
                    ),
                ),
                (
                    "raw_body",
                    models.FileField(
                        blank=True,
                        help_text="Raw RFC 822 message bytes.",
                        upload_to="messages/",
                        verbose_name="raw body",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="RFC 5322 header fields of the message, as [name, value] pairs.",
                        verbose_name="headers",
                    ),
                ),
                (
                    "spam_score",
                    models.FloatField(
                        blank=True,
                        help_text="rspamd score assigned to the message.",
                        null=True,
                        verbose_name="spam score",
                    ),
                ),
                (
                    "spam_action",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("pass", "pass"),
                            ("no action", "pass"),
                            ("greylist", "greylist"),
                            ("add header", "add header"),
                            ("rewrite subject", "rewrite subject"),
                            ("soft reject", "soft reject"),
                            ("reject", "reject"),
                            ("drop", "drop"),
                        ],
                        help_text="rspamd action assigned to the message.",
                        verbose_name="spam action",
                    ),
                ),
                (
                    "virus_action",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("clean", "no virus"),
                            ("infected", "virus"),
                            ("encrypted", "encrypted part"),
                            ("macro", "macro"),
                            ("limits", "scan limits"),
                        ],
                        help_text="Antivirus verdict derived from the rspamd symbols, empty until a check completes.",
                        verbose_name="virus action",
                    ),
                ),
                (
                    "virus_name",
                    models.TextField(
                        blank=True,
                        help_text="Name of the virus rspamd detected, empty when it found none.",
                        verbose_name="virus name",
                    ),
                ),
                (
                    "virus_symbols",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Antivirus symbols rspamd reported for the message.",
                        verbose_name="virus symbols",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        help_text="Delivery lifecycle state.", verbose_name="status"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        help_text="Domain associated with this message.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="domains.domain",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpamCheck",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing started.",
                        verbose_name="started",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing finished.",
                        verbose_name="finished",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="rspamd score the check returned, or null when the check failed.",
                        null=True,
                        verbose_name="score",
                    ),
                ),
                (
                    "scan_ms",
                    models.FloatField(
                        blank=True,
                        help_text="Milliseconds rspamd measured for the check itself.",
                        null=True,
                        verbose_name="scan time",
                    ),
                ),
                (
                    "antivirus_ms",
                    models.FloatField(
                        blank=True,
                        help_text="Milliseconds the antivirus took, or null when rspamd did not profile the check.",
                        null=True,
                        verbose_name="antivirus time",
                    ),
                ),
                (
                    "profile_ms",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Milliseconds rspamd spent per symbol, empty when it did not profile the check.",
                        verbose_name="profile",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "spam check",
                "ordering": ["started_at", "created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing started.",
                        verbose_name="started",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing finished.",
                        verbose_name="finished",
                    ),
                ),
                (
                    "remote_host",
                    models.TextField(
                        blank=True,
                        help_text="Hostname of the remote peer of this leg, when known.",
                        verbose_name="remote host",
                    ),
                ),
                (
                    "local_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address relay used for this leg.",
                        null=True,
                        verbose_name="local IP address",
                    ),
                ),
                (
                    "remote_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the remote peer of this leg.",
                        null=True,
                        verbose_name="remote IP address",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("received", "received"),
                            ("submitted", "submitted"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                            ("retry", "retry"),
                            ("bounced", "bounced"),
                        ],
                        help_text="Outcome of this delivery attempt.",
                        verbose_name="status",
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="SMTP response code from the remote server.",
                        null=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        help_text="Raw SMTP transcript from the remote server.",
                        verbose_name="output",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable explanation of the outcome.",
                        verbose_name="details",
                    ),
                ),
                (
                    "tls_mode",
                    models.TextField(
                        choices=[
                            ("plaintext", "plaintext"),
                            ("starttls", "STARTTLS"),
                            ("tls", "TLS"),
                        ],
                        default="plaintext",
                        help_text="TLS transport negotiated for this leg.",
                        verbose_name="TLS mode",
                    ),
                ),
                (
                    "tls_version",
                    models.TextField(
                        blank=True,
                        help_text="Negotiated TLS protocol version, for example TLSv1.3.",
                        verbose_name="TLS version",
                    ),
                ),
                (
                    "tls_cipher",
                    models.TextField(
                        blank=True,
                        help_text="Negotiated TLS cipher suite.",
                        verbose_name="TLS cipher",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmissions",
                        to="message.message",
                    ),
                ),
                (
                    "tls_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmissions",
                        to="kms.certificate",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at", "created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["status"], name="message_mes_status_92ccc6_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["domain", "status"], name="message_mes_domain__fbf48a_idx"
            ),
        ),
    ]
