# Generated by Django 6.1.1 on 2026-09-16 18:42

from django.db import migrations, models

import services.email.message.models


def truncate_messages(apps, schema_editor):
    """Delete every stored message and the rows that reference it."""
    message = apps.get_model("message", "Message")
    if schema_editor.connection.vendor == "postgresql":
        table = schema_editor.connection.ops.quote_name(message._meta.db_table)
        schema_editor.execute(f"TRUNCATE {table} CASCADE")
    else:
        message.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        # The delete cascades into the models that reference a message.
        ("dmarc", "0001_initial"),
        ("message", "0001_initial"),
        ("msa", "0001_initial"),
        ("mta", "0001_initial"),
        ("reputation", "0001_initial"),
    ]

    operations = [
        # Bodies written before this migration share one storage object, so
        # they belong to no particular row and cannot be kept.
        migrations.RunPython(truncate_messages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="message",
            name="raw_body",
            field=models.FileField(
                blank=True,
                help_text="Raw RFC 822 message bytes.",
                upload_to=services.email.message.models.create_raw_body_path,
                verbose_name="raw body",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("raw_body", ""), _negated=True),
                fields=("raw_body",),
                name="unique_message_body",
            ),
        ),
    ]
