# Generated by Django 6.1.1 on 2026-09-16 18:42

from django.db import migrations, models

import services.email.message.models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="raw_body",
            field=models.FileField(
                blank=True,
                help_text="Raw RFC 822 message bytes.",
                upload_to=services.email.message.models.create_raw_body_path,
                verbose_name="raw body",
            ),
        ),
    ]
