# Generated by Django 6.1rc1 on 2026-08-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0001_initial"),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="domain",
            field=models.ForeignKey(
                help_text="Domain associated with this message.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="domains.domain",
            ),
        ),
    ]
