# Generated by Django 6.1 on 2026-08-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="org_encryption_key_id",
            field=models.TextField(
                blank=True,
                help_text="Fingerprint of the org encryption key used to seal the file key.",
                verbose_name="org encryption key ID",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sealed_file_key",
            field=models.TextField(
                blank=True,
                help_text="File key sealed with the org's active X25519 public key. Unsealed client-side with the org private key.",
                verbose_name="sealed file key",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="raw_body",
            field=models.FileField(
                blank=True,
                help_text="Encrypted raw RFC 822 message bytes.",
                upload_to="messages/",
                verbose_name="raw body",
            ),
        ),
    ]
