# Generated by Django 6.1 on 2026-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="spam_action",
            field=models.TextField(
                blank=True,
                help_text="rspamd action assigned to the message.",
                verbose_name="spam action",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="spam_score",
            field=models.FloatField(
                blank=True,
                help_text="rspamd score assigned to the message.",
                null=True,
                verbose_name="spam score",
            ),
        ),
    ]
