# Generated by Django 6.1 on 2026-08-29 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0001_initial"),
        ("message", "0002_message_spam_action_message_spam_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="domain",
            field=models.ForeignKey(
                help_text="Domain associated with this message.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="domains.domain",
            ),
        ),
    ]
