# Generated by Django 6.1 on 2026-08-22 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0002_message_org_encryption_key_id_and_more"),
        ("message", "0002_message_spam_action_message_spam_score"),
    ]

    operations = []
