# Generated by Django 6.1 on 2026-08-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0003_alter_message_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="headers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="RFC 5322 header fields of the message, as [name, value] pairs.",
                verbose_name="headers",
            ),
        ),
    ]
