# Generated by Django 6.1 on 2026-09-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0004_message_headers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="spam_action",
            field=models.TextField(
                blank=True,
                choices=[
                    ("pass", "pass"),
                    ("no action", "no action"),
                    ("greylist", "greylist"),
                    ("add header", "add header"),
                    ("rewrite subject", "rewrite subject"),
                    ("soft reject", "soft reject"),
                    ("reject", "reject"),
                    ("drop", "drop"),
                ],
                help_text="rspamd action assigned to the message.",
                verbose_name="spam action",
            ),
        ),
    ]
