# Generated by Django 6.1 on 2026-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0005_alter_message_spam_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.TextField(
                blank=True,
                help_text="Subject header value with RFC 2047 encoded-words decoded.",
                verbose_name="subject",
            ),
        ),
    ]
