# Generated by Django 6.1.1 on 2026-09-08 15:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0007_decode_stored_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timing",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text=(
                            "Processing stage this timing measured, for example spam-check."
                        ),
                        verbose_name="stage",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="When this stage started.", verbose_name="started"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        help_text="When this stage ended.", verbose_name="finished"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timings",
                        to="message.message",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at", "created_at"],
                "get_latest_by": "created_at",
                "indexes": [
                    models.Index(
                        fields=["message", "started_at"],
                        name="message_tim_message_d6392a_idx",
                    )
                ],
            },
        ),
    ]
