# Generated by Django 6.1.1 on 2026-09-09 20:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


def backfill_receptions(apps, schema_editor):
    """Record the reception transmission of every inbound message on file."""
    transmission_model = apps.get_model("message", "transmission")
    incoming_messages = apps.get_model("mta", "incomingmessage").objects.all()
    for message in incoming_messages:
        transmission_model.objects.create(
            message=message,
            status="received",
            tls_mode=("starttls" if message.received_with_tls else "plaintext"),
            tls_version=message.tls_version,
            tls_cipher=message.tls_cipher,
            tls_certificate_id=message.tls_certificate_id,
            started_at=message.created_at,
            finished_at=message.created_at,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("kms", "0003_certificate"),
        ("message", "0007_decode_stored_subjects"),
        ("mta", "0003_webhookdelivery_timing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="received_with_tls",
        ),
        migrations.AlterField(
            model_name="message",
            name="spam_action",
            field=models.TextField(
                blank=True,
                choices=[
                    ("pass", "pass"),
                    ("no action", "pass"),
                    ("greylist", "greylist"),
                    ("add header", "add header"),
                    ("rewrite subject", "rewrite subject"),
                    ("soft reject", "soft reject"),
                    ("reject", "reject"),
                    ("drop", "drop"),
                ],
                help_text="rspamd action assigned to the message.",
                verbose_name="spam action",
            ),
        ),
        migrations.CreateModel(
            name="SpamCheck",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing started.",
                        verbose_name="started",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing finished.",
                        verbose_name="finished",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="rspamd score the check returned, or null when the check failed.",
                        null=True,
                        verbose_name="score",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "spam check",
                "ordering": ["started_at", "created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing started.",
                        verbose_name="started",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing finished.",
                        verbose_name="finished",
                    ),
                ),
                (
                    "remote_host",
                    models.TextField(
                        blank=True,
                        help_text="Hostname of the remote peer of this leg, when known.",
                        verbose_name="remote host",
                    ),
                ),
                (
                    "local_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address relay used for this leg.",
                        null=True,
                        verbose_name="local IP address",
                    ),
                ),
                (
                    "remote_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the remote peer of this leg.",
                        null=True,
                        verbose_name="remote IP address",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("received", "received"),
                            ("submitted", "submitted"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                            ("retry", "retry"),
                            ("bounced", "bounced"),
                        ],
                        help_text="Outcome of this delivery attempt.",
                        verbose_name="status",
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="SMTP response code from the remote server.",
                        null=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        help_text="Raw SMTP transcript from the remote server.",
                        verbose_name="output",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable explanation of the outcome.",
                        verbose_name="details",
                    ),
                ),
                (
                    "tls_mode",
                    models.TextField(
                        choices=[
                            ("plaintext", "plaintext"),
                            ("starttls", "STARTTLS"),
                            ("tls", "TLS"),
                        ],
                        default="plaintext",
                        help_text="TLS transport negotiated for this leg.",
                        verbose_name="TLS mode",
                    ),
                ),
                (
                    "tls_version",
                    models.TextField(
                        blank=True,
                        help_text="Negotiated TLS protocol version, for example TLSv1.3.",
                        verbose_name="TLS version",
                    ),
                ),
                (
                    "tls_cipher",
                    models.TextField(
                        blank=True,
                        help_text="Negotiated TLS cipher suite.",
                        verbose_name="TLS cipher",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmissions",
                        to="message.message",
                    ),
                ),
                (
                    "tls_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmissions",
                        to="kms.certificate",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at", "created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.RunPython(backfill_receptions, migrations.RunPython.noop),
    ]
