# Generated by Django 6.1.1 on 2026-09-09 19:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kms", "0003_certificate"),
        ("message", "0007_decode_stored_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="spam_action",
            field=models.TextField(
                blank=True,
                choices=[
                    ("pass", "pass"),
                    ("no action", "pass"),
                    ("greylist", "greylist"),
                    ("add header", "add header"),
                    ("rewrite subject", "rewrite subject"),
                    ("soft reject", "soft reject"),
                    ("reject", "reject"),
                    ("drop", "drop"),
                ],
                help_text="rspamd action assigned to the message.",
                verbose_name="spam action",
            ),
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing started.",
                        verbose_name="started",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing finished.",
                        verbose_name="finished",
                    ),
                ),
                (
                    "mx_host",
                    models.TextField(
                        blank=True,
                        help_text="MX hostname this delivery attempt dialed.",
                        verbose_name="MX host",
                    ),
                ),
                (
                    "local_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address relay used for this leg.",
                        null=True,
                        verbose_name="local IP address",
                    ),
                ),
                (
                    "remote_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the remote peer of this leg.",
                        null=True,
                        verbose_name="remote IP address",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("received", "received"),
                            ("submitted", "submitted"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                            ("retry", "retry"),
                            ("bounced", "bounced"),
                        ],
                        help_text="Outcome of this delivery attempt.",
                        verbose_name="status",
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="SMTP response code from the remote server.",
                        null=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        help_text="Raw SMTP transcript from the remote server.",
                        verbose_name="output",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable explanation of the outcome.",
                        verbose_name="details",
                    ),
                ),
                (
                    "tls_mode",
                    models.TextField(
                        choices=[
                            ("plaintext", "plaintext"),
                            ("starttls", "STARTTLS"),
                            ("tls", "TLS"),
                        ],
                        default="plaintext",
                        help_text="TLS transport negotiated for this leg.",
                        verbose_name="TLS mode",
                    ),
                ),
                (
                    "tls_version",
                    models.TextField(
                        blank=True,
                        help_text="Negotiated TLS protocol version, for example TLSv1.3.",
                        verbose_name="TLS version",
                    ),
                ),
                (
                    "tls_cipher",
                    models.TextField(
                        blank=True,
                        help_text="Negotiated TLS cipher suite.",
                        verbose_name="TLS cipher",
                    ),
                ),
                (
                    "log_id",
                    models.TextField(
                        blank=True,
                        help_text="Remote server log identifier.",
                        verbose_name="log ID",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmissions",
                        to="message.message",
                    ),
                ),
                (
                    "tls_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmissions",
                        to="kms.certificate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
