# Generated by Django 6.1.1 on 2026-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0008_remove_message_received_with_tls_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="virus_action",
            field=models.TextField(
                blank=True,
                choices=[
                    ("clean", "no virus"),
                    ("infected", "virus"),
                    ("encrypted", "encrypted part"),
                    ("macro", "macro"),
                    ("limits", "scan limits"),
                ],
                help_text="Antivirus verdict derived from the rspamd symbols, empty until a check completes.",
                verbose_name="virus action",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="virus_name",
            field=models.TextField(
                blank=True,
                help_text="Name of the virus rspamd detected, empty when it found none.",
                verbose_name="virus name",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="virus_symbols",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Antivirus symbols rspamd reported for the message.",
                verbose_name="virus symbols",
            ),
        ),
    ]
