# Generated by Django 6.1.1 on 2026-09-09 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0008_transmission"),
        ("mta", "0004_remove_incomingmessage_tls_certificate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="received_with_tls",
        ),
    ]
