# Generated by Django 6.1.1 on 2026-09-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0009_message_virus_action_message_virus_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spamcheck",
            name="antivirus_ms",
            field=models.FloatField(
                blank=True,
                help_text="Milliseconds the antivirus took, or null when rspamd did not profile the check.",
                null=True,
                verbose_name="antivirus time",
            ),
        ),
        migrations.AddField(
            model_name="spamcheck",
            name="profile_ms",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Milliseconds rspamd spent per symbol, empty when it did not profile the check.",
                verbose_name="profile",
            ),
        ),
        migrations.AddField(
            model_name="spamcheck",
            name="scan_ms",
            field=models.FloatField(
                blank=True,
                help_text="Milliseconds rspamd measured for the check itself.",
                null=True,
                verbose_name="scan time",
            ),
        ),
    ]
