# Generated by Django 6.1.1 on 2026-09-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "fingerprint",
                    models.TextField(
                        help_text="SHA-256 fingerprint of the certificate, as lowercase hex.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="fingerprint",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        blank=True,
                        help_text="Subject of the certificate, in RFC 4514 notation.",
                        verbose_name="subject",
                    ),
                ),
                (
                    "subject_alternative_names",
                    models.TextField(
                        blank=True,
                        help_text="DNS names the certificate covers, comma-separated.",
                        verbose_name="subject alternative names",
                    ),
                ),
                (
                    "issuer",
                    models.TextField(
                        blank=True,
                        help_text="Subject of the authority that signed the certificate.",
                        verbose_name="issuer",
                    ),
                ),
                (
                    "serial_number",
                    models.TextField(
                        blank=True,
                        help_text="Serial number of the certificate, as lowercase hex.",
                        verbose_name="serial number",
                    ),
                ),
                (
                    "not_before",
                    models.DateTimeField(
                        blank=True,
                        help_text="Point in time from which the certificate is valid.",
                        null=True,
                        verbose_name="valid from",
                    ),
                ),
                (
                    "not_after",
                    models.DateTimeField(
                        blank=True,
                        help_text="Point in time until which the certificate is valid.",
                        null=True,
                        verbose_name="valid until",
                    ),
                ),
                (
                    "issuer_certificate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Certificate that signed this certificate, when presented.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_certificates",
                        to="kms.certificate",
                        verbose_name="issuer certificate",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SigningKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "algorithm",
                    models.TextField(
                        choices=[("rsa-2048", "RSA 2048"), ("ed25519", "Ed25519")],
                        help_text="Public-key algorithm and size used to sign.",
                        verbose_name="algorithm",
                    ),
                ),
                (
                    "encrypted_private_key",
                    models.TextField(
                        help_text="Fernet-encrypted PKCS#8 PEM.",
                        verbose_name="encrypted private key",
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="Plaintext public PEM. Shareable with verifiers.",
                        verbose_name="public key",
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        editable=False,
                        help_text="Short SHA256 fingerprint of the public key.",
                        max_length=16,
                        verbose_name="key ID",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("algorithm", "key_id"),
                        name="unique_signing_key_id_per_algorithm",
                    )
                ],
            },
        ),
    ]
