# Generated by Django 6.0.6 on 2026-07-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SigningKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("rsa-2048", "RSA 2048"),
                            ("rsa-1024", "RSA 1024"),
                            ("ed25519", "Ed25519"),
                        ],
                        help_text="Public-key algorithm and size used to sign.",
                        max_length=8,
                        verbose_name="algorithm",
                    ),
                ),
                (
                    "encrypted_private_key",
                    models.TextField(
                        help_text="Fernet-encrypted PKCS#8 PEM.",
                        verbose_name="encrypted private key",
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="Plaintext public PEM — shareable with verifiers.",
                        verbose_name="public key",
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        editable=False,
                        help_text="Short SHA256 fingerprint of the public key.",
                        max_length=16,
                        verbose_name="key ID",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("algorithm", "key_id"),
                        name="unique_signing_key_id_per_algorithm",
                    )
                ],
            },
        ),
    ]
