# Generated by Django 6.1 on 2026-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signingkey",
            name="algorithm",
            field=models.TextField(
                choices=[("rsa-2048", "RSA 2048"), ("ed25519", "Ed25519")],
                help_text="Public-key algorithm and size used to sign.",
                verbose_name="algorithm",
            ),
        ),
    ]
