# Generated by Django 6.1 on 2026-08-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userencryptionkey_membershipencryptionkey"),
        ("kms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgEncryptionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="Base64-encoded X25519 public key used to seal file keys.",
                        verbose_name="public key",
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        editable=False,
                        help_text="Short SHA256 fingerprint of the public key.",
                        max_length=16,
                        verbose_name="key ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only the active key is used to seal new file keys.",
                        verbose_name="active",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_keys",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "key_id"),
                        name="unique_org_encryption_key_id_per_org",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("org",),
                        name="unique_active_org_encryption_key_per_org",
                    ),
                ],
            },
        ),
    ]
