# Generated by Django 6.1rc1 on 2026-08-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signingkey",
            name="algorithm",
            field=models.TextField(
                choices=[
                    ("rsa-2048", "RSA 2048"),
                    ("rsa-1024", "RSA 1024"),
                    ("ed25519", "Ed25519"),
                ],
                help_text="Public-key algorithm and size used to sign.",
                verbose_name="algorithm",
            ),
        ),
    ]
