# Generated by Django 6.0.6 on 2026-07-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kms", "0002_rename_private_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signingkey",
            name="encrypted_private_key",
            field=models.TextField(
                help_text="Fernet-encrypted PKCS#8 PEM.",
                verbose_name="encrypted private key",
            ),
        ),
    ]
