# Generated by Django 6.1 on 2026-08-15 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kms", "0002_orgencryptionkey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orgencryptionkey",
            name="recovery_sealed_org_private_key",
            field=models.TextField(
                blank=True,
                help_text="Org private key encrypted with a KEK derived from a BIP39 mnemonic. Used for break-glass recovery. Format: base64 of salt + nonce + ciphertext.",
                verbose_name="recovery sealed org private key",
            ),
        ),
        migrations.CreateModel(
            name="RecoveryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "org_encryption_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_events",
                        to="kms.orgencryptionkey",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        help_text="User who entered the recovery mnemonic.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
