# Generated by Django 6.1 on 2026-08-31 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kms", "0002_alter_signingkey_algorithm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "fingerprint",
                    models.TextField(
                        help_text="SHA-256 fingerprint of the certificate, as lowercase hex.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="fingerprint",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        blank=True,
                        help_text="Subject of the certificate, in RFC 4514 notation.",
                        verbose_name="subject",
                    ),
                ),
                (
                    "subject_alternative_names",
                    models.TextField(
                        blank=True,
                        help_text="DNS names the certificate covers, comma-separated.",
                        verbose_name="subject alternative names",
                    ),
                ),
                (
                    "issuer",
                    models.TextField(
                        blank=True,
                        help_text="Subject of the authority that signed the certificate.",
                        verbose_name="issuer",
                    ),
                ),
                (
                    "serial_number",
                    models.TextField(
                        blank=True,
                        help_text="Serial number of the certificate, as lowercase hex.",
                        verbose_name="serial number",
                    ),
                ),
                (
                    "not_before",
                    models.DateTimeField(
                        blank=True,
                        help_text="Point in time from which the certificate is valid.",
                        null=True,
                        verbose_name="valid from",
                    ),
                ),
                (
                    "not_after",
                    models.DateTimeField(
                        blank=True,
                        help_text="Point in time until which the certificate is valid.",
                        null=True,
                        verbose_name="valid until",
                    ),
                ),
                (
                    "issuer_certificate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Certificate that signed this certificate, when presented.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_certificates",
                        to="kms.certificate",
                        verbose_name="issuer certificate",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
