# Generated by Django 6.1 on 2026-08-15 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kms", "0003_orgencryptionkey_recovery_sealed_org_private_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recoveryevent",
            name="org_encryption_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recovery_events",
                to="kms.orgencryptionkey",
            ),
        ),
        migrations.AlterField(
            model_name="recoveryevent",
            name="triggered_by",
            field=models.ForeignKey(
                help_text="User who entered the recovery mnemonic.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
