# Generated by Django 6.1.1 on 2026-09-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="billing_is_active",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether billing is active for the organization.",
                verbose_name="billing is active",
            ),
        ),
    ]
