# Generated by Django 6.1 on 2026-08-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="suspended_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Suspended organizations cannot send outgoing messages.",
                null=True,
                verbose_name="suspended at",
            ),
        ),
    ]
