# Generated by Django 6.1 on 2026-08-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="reputation_locked",
            field=models.BooleanField(
                default=False,
                help_text="Locked organizations cannot send outgoing messages.",
                verbose_name="reputation locked",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="reputation_locked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the organization was locked for sender reputation.",
                null=True,
                verbose_name="reputation locked at",
            ),
        ),
    ]
