# Generated by Django 6.1rc1 on 2026-08-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="billing_is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether the organization has active billing. When inactive, sending and receiving is restricted to organization members.",
                verbose_name="billing active",
            ),
        ),
    ]
