# Generated by Django 6.1rc1 on 2026-08-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.TextField(
                choices=[("write", "write"), ("admin", "admin")],
                default="write",
                help_text="Write members can use services. Admin members can also manage users.",
                verbose_name="role",
            ),
        ),
    ]
