# Generated by Django 6.1 on 2026-08-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenSourceApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Project or community applying for the free service.",
                        verbose_name="name",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        help_text="Where the project or community lives online.",
                        verbose_name="website",
                    ),
                ),
                (
                    "repository",
                    models.URLField(
                        blank=True,
                        help_text="Link to the public source code, if any.",
                        verbose_name="repository",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Address we reply to.",
                        max_length=254,
                        verbose_name="contact email",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="What the community runs and what it needs.",
                        verbose_name="message",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("declined", "declined"),
                        ],
                        default="pending",
                        help_text="Review state of the application.",
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
