# Generated by Django 6.1 on 2026-08-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEncryptionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="Base64-encoded X25519 public key.",
                        verbose_name="public key",
                    ),
                ),
                (
                    "encrypted_master_key",
                    models.TextField(
                        help_text="Master Key encrypted with the KEK derived from the user's encryption passphrase. Decrypted client-side only.",
                        verbose_name="encrypted master key",
                    ),
                ),
                (
                    "encrypted_private_key",
                    models.TextField(
                        help_text="X25519 private key encrypted with the Master Key. Decrypted client-side only.",
                        verbose_name="encrypted private key",
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        editable=False,
                        help_text="Short SHA256 fingerprint of the public key.",
                        max_length=16,
                        verbose_name="key ID",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MembershipEncryptionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "sealed_org_private_key",
                    models.TextField(
                        help_text="Org X25519 private key sealed with the member's public key via crypto_box_seal. Unsealed client-side only.",
                        verbose_name="sealed org private key",
                    ),
                ),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_key",
                        to="accounts.membership",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
