# Generated by Django 6.1 on 2026-08-15 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userencryptionkey_membershipencryptionkey"),
        ("kms", "0002_orgencryptionkey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipencryptionkey",
            name="org_encryption_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_keys",
                to="kms.orgencryptionkey",
            ),
        ),
        migrations.AddField(
            model_name="userencryptionkey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encryption_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userencryptionkey",
            constraint=models.UniqueConstraint(
                fields=("user", "key_id"), name="unique_user_encryption_key_id_per_user"
            ),
        ),
    ]
