# Generated by Django 6.1 on 2026-08-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mx", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEncryptionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="Base64-encoded X25519 public key for the webhook recipient.",
                        verbose_name="public key",
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        editable=False,
                        help_text="Short SHA256 fingerprint of the public key.",
                        max_length=16,
                        verbose_name="key ID",
                    ),
                ),
                (
                    "webhook",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_key",
                        to="mx.webhook",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SealedFileKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "sealed_key",
                    models.TextField(
                        help_text="File key sealed with the webhook's X25519 public key via crypto_box_seal.",
                        verbose_name="sealed key",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sealed_file_keys",
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sealed_file_keys",
                        to="mx.webhook",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "webhook"),
                        name="unique_sealed_file_key_per_message_webhook",
                    )
                ],
            },
        ),
    ]
