# Generated by Django 6.1rc1 on 2026-08-01 17:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[("incoming", "incoming"), ("outgoing", "outgoing")],
                        verbose_name="kind",
                    ),
                ),
                (
                    "mail_from",
                    models.EmailField(
                        help_text="Envelope sender address (MAIL FROM).",
                        max_length=254,
                        verbose_name="mail from",
                    ),
                ),
                (
                    "rcpt_to",
                    models.TextField(
                        help_text="Envelope recipient address(es) (RCPT TO).",
                        verbose_name="rcpt to",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        blank=True,
                        help_text="RFC 5322 Subject header value.",
                        verbose_name="subject",
                    ),
                ),
                (
                    "message_id",
                    models.TextField(
                        blank=True,
                        help_text="RFC 5322 Message-ID header.",
                        verbose_name="message ID",
                    ),
                ),
                (
                    "raw_body",
                    models.FileField(
                        blank=True,
                        help_text="Raw RFC 822 message bytes.",
                        upload_to="messages/",
                        verbose_name="raw body",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the message was accepted.",
                        verbose_name="received at",
                    ),
                ),
                (
                    "received_with_tls",
                    models.BooleanField(
                        default=False,
                        help_text="Submission received over TLS.",
                        verbose_name="received with TLS",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
