# Generated by Django 6.1rc1 on 2026-08-01 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tx_mail", "0002_signing_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="modified_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="received_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the message was accepted.",
                verbose_name="received at",
            ),
        ),
    ]
