"""
The CSS a Gmail preview drops, from the caniemail.com support data.

Gmail reads no prefers-color-scheme query of its own, so the color scheme stays
with the preview theme.
"""

from .. import styles

# Selectors with a pseudo-class or pseudo-element Gmail does not support.
PSEUDOS = (
    r"::?(?:active|checked|default|first-child|first-of-type|focus|focus-visible"
    r"|focus-within|has|lang|last-child|last-of-type|link|not|nth-child"
    r"|nth-last-child|nth-last-of-type|nth-of-type|only-child|only-of-type"
    r"|target|visited|after|before|first-letter|first-line|marker|placeholder)\b"
)

# Declarations caniemail.com marks unsupported for Gmail.
PROPERTIES = frozenset(
    {
        "accent-color",
        "align-items",
        "animation",
        "animation-delay",
        "animation-direction",
        "animation-duration",
        "animation-fill-mode",
        "animation-iteration-count",
        "animation-name",
        "animation-play-state",
        "animation-timing-function",
        "aspect-ratio",
        "backdrop-filter",
        "block-size",
        "border-block",
        "border-block-color",
        "border-block-end",
        "border-block-end-color",
        "border-block-end-style",
        "border-block-end-width",
        "border-block-start",
        "border-block-start-color",
        "border-block-start-style",
        "border-block-start-width",
        "border-block-style",
        "border-block-width",
        "border-end-end-radius",
        "border-end-start-radius",
        "border-image",
        "border-image-outset",
        "border-image-repeat",
        "border-image-slice",
        "border-image-source",
        "border-image-width",
        "border-inline",
        "border-inline-color",
        "border-inline-end",
        "border-inline-end-color",
        "border-inline-end-style",
        "border-inline-end-width",
        "border-inline-start",
        "border-inline-start-color",
        "border-inline-start-style",
        "border-inline-start-width",
        "border-inline-style",
        "border-inline-width",
        "border-start-end-radius",
        "border-start-start-radius",
        "bottom",
        "box-shadow",
        "clip-path",
        "color-scheme",
        "cursor",
        "filter",
        "flex-direction",
        "flex-wrap",
        "grid-template",
        "grid-template-areas",
        "grid-template-columns",
        "grid-template-rows",
        "hyphenate-character",
        "hyphenate-limit-chars",
        "hyphens",
        "inline-size",
        "inset",
        "inset-block",
        "inset-block-end",
        "inset-block-start",
        "inset-inline",
        "inset-inline-end",
        "inset-inline-start",
        "justify-content",
        "left",
        "list-style-image",
        "margin-block",
        "margin-block-end",
        "margin-block-start",
        "margin-inline",
        "margin-inline-end",
        "margin-inline-start",
        "mask-image",
        "max-block-size",
        "max-inline-size",
        "min-block-size",
        "min-inline-size",
        "orphans",
        "outline-offset",
        "overflow-wrap",
        "padding-block",
        "padding-block-end",
        "padding-block-start",
        "padding-inline",
        "padding-inline-end",
        "padding-inline-start",
        "position",
        "resize",
        "right",
        "scroll-snap-align",
        "scroll-snap-stop",
        "scroll-snap-type",
        "shape-margin",
        "shape-outside",
        "tab-size",
        "text-decoration-skip-ink",
        "text-decoration-thickness",
        "text-emphasis",
        "text-emphasis-color",
        "text-emphasis-position",
        "text-emphasis-style",
        "text-shadow",
        "text-underline-offset",
        "text-wrap",
        "top",
        "transform",
        "transition",
        "transition-delay",
        "transition-duration",
        "transition-property",
        "transition-timing-function",
        "user-select",
        "visibility",
        "white-space-collapse",
        "widows",
        "z-index",
    }
)

RESTRICTIONS = styles.Restrictions(
    properties=PROPERTIES,
    # Modern color functions and conic gradients do not apply in Gmail.
    values=(r"\b(?:lch|oklch|lab|oklab)\(", r"\blight-dark\(", r"\bconic-gradient\("),
    # These at-rules do not apply, and Gmail reads no hover or motion query.
    at_rules=frozenset({"@font-face", "@import", "@keyframes", "@supports"}),
    media_terms=(
        r"prefers-reduced-motion",
        r"\bhover\b",
        r"-webkit-device-pixel-ratio",
    ),
    selectors=(PSEUDOS,),
    custom_properties=True,
)
