# Generated by Django 6.1rc1 on 2026-08-03 17:24

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

import domains.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("kms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Root domain, for example acme.com.",
                        max_length=255,
                        unique=True,
                        validators=[domains.models.validate_domain_name],
                        verbose_name="name",
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        default=domains.models.generate_verification_token,
                        editable=False,
                        help_text="Token published in DNS to prove ownership.",
                        max_length=16,
                        verbose_name="verification token",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When DNS verification completed.",
                        null=True,
                        verbose_name="verified at",
                    ),
                ),
                (
                    "nameserver_status",
                    models.TextField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("pending", "pending"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="NS delegation check result for the sender subdomain.",
                        verbose_name="nameserver status",
                    ),
                ),
                (
                    "nameserver_error",
                    models.TextField(
                        blank=True,
                        help_text="Failure detail if NS delegation is incorrect.",
                        verbose_name="nameserver error",
                    ),
                ),
                (
                    "spf_status",
                    models.TextField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("pending", "pending"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="SPF record check result on the root domain.",
                        verbose_name="SPF status",
                    ),
                ),
                (
                    "spf_error",
                    models.TextField(
                        blank=True,
                        help_text="Failure detail if the SPF record is incorrect.",
                        verbose_name="SPF error",
                    ),
                ),
                (
                    "dkim_status",
                    models.TextField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("pending", "pending"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="DKIM CNAME check result on the root domain.",
                        verbose_name="DKIM status",
                    ),
                ),
                (
                    "dkim_error",
                    models.TextField(
                        blank=True,
                        help_text="Failure detail if the DKIM CNAME is incorrect.",
                        verbose_name="DKIM error",
                    ),
                ),
                (
                    "dmarc_status",
                    models.TextField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("pending", "pending"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="DMARC record check result on the root domain.",
                        verbose_name="DMARC status",
                    ),
                ),
                (
                    "dmarc_error",
                    models.TextField(
                        blank=True,
                        help_text="Failure detail if the DMARC record is incorrect.",
                        verbose_name="DMARC error",
                    ),
                ),
                (
                    "mta_sts_status",
                    models.TextField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("pending", "pending"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="MTA-STS record check result on the root domain.",
                        verbose_name="MTA-STS status",
                    ),
                ),
                (
                    "mta_sts_error",
                    models.TextField(
                        blank=True,
                        help_text="Failure detail if the MTA-STS record is incorrect.",
                        verbose_name="MTA-STS error",
                    ),
                ),
                (
                    "tls_rpt_status",
                    models.TextField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("pending", "pending"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="TLS-RPT record check result on the root domain.",
                        verbose_name="TLS-RPT status",
                    ),
                ),
                (
                    "tls_rpt_error",
                    models.TextField(
                        blank=True,
                        help_text="Failure detail if the TLS-RPT record is incorrect.",
                        verbose_name="TLS-RPT error",
                    ),
                ),
                (
                    "dns_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last DNS check timestamp.",
                        null=True,
                        verbose_name="DNS checked at",
                    ),
                ),
                (
                    "dkim_key_ed25519",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ed25519 DKIM signing key.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="kms.signingkey",
                    ),
                ),
                (
                    "dkim_key_rsa1024",
                    models.ForeignKey(
                        blank=True,
                        help_text="RSA-1024 DKIM signing key. For compatibility with older verifiers.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="kms.signingkey",
                    ),
                ),
                (
                    "dkim_key_rsa2048",
                    models.ForeignKey(
                        blank=True,
                        help_text="RSA-2048 DKIM signing key.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="kms.signingkey",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization. Null for system domains.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="accounts.organization",
                    ),
                ),
                (
                    "is_managed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether relay manages this domain's DNS automatically.",
                        verbose_name="managed",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("name"),
                        name="domain_name_lower_idx",
                    )
                ],
            },
        ),
    ]
