# Generated by Django 6.0.5 on 2026-07-18 17:07

import django.db.models.deletion
import domains.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=domains.models.generate_credential_key,
                        editable=False,
                        help_text="Auto-generated API key for SMTP authentication.",
                        max_length=24,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("smtp", "SMTP"), ("smtp-ip", "SMTP-IP")],
                        default="smtp",
                        help_text="Credential type for SMTP authentication.",
                        max_length=7,
                        verbose_name="type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label for this credential.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this credential was last used for SMTP auth.",
                        null=True,
                        verbose_name="last used",
                    ),
                ),
                (
                    "hold",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this credential is suspended and cannot be used.",
                        verbose_name="hold",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Sender domain name, e.g. example.com.",
                        max_length=255,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        default=domains.models.generate_verification_token,
                        editable=False,
                        help_text="Token placed in DNS for domain verification.",
                        max_length=16,
                        verbose_name="verification token",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this domain was verified.",
                        null=True,
                        verbose_name="verified at",
                    ),
                ),
                (
                    "ns_status",
                    models.CharField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("pending", "pending"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="Status of NS delegation verification.",
                        max_length=9,
                        verbose_name="NS status",
                    ),
                ),
                (
                    "ns_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if NS verification failed.",
                        verbose_name="NS error",
                    ),
                ),
                (
                    "spf_status",
                    models.CharField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("pending", "pending"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="Status of SPF record verification.",
                        max_length=9,
                        verbose_name="SPF status",
                    ),
                ),
                (
                    "spf_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if SPF verification failed.",
                        verbose_name="SPF error",
                    ),
                ),
                (
                    "dkim_status",
                    models.CharField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("pending", "pending"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="Status of DKIM CNAME verification.",
                        max_length=9,
                        verbose_name="DKIM status",
                    ),
                ),
                (
                    "dkim_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if DKIM verification failed.",
                        verbose_name="DKIM error",
                    ),
                ),
                (
                    "dmarc_status",
                    models.CharField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "error"),
                            ("pending", "pending"),
                            ("unchecked", "unchecked"),
                        ],
                        default="unchecked",
                        help_text="Status of DMARC record verification.",
                        max_length=9,
                        verbose_name="DMARC status",
                    ),
                ),
                (
                    "dmarc_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if DMARC verification failed.",
                        verbose_name="DMARC error",
                    ),
                ),
                (
                    "dns_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When DNS checks were last run.",
                        null=True,
                        verbose_name="DNS checked at",
                    ),
                ),
                (
                    "outgoing",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this domain can send email.",
                        verbose_name="outgoing",
                    ),
                ),
                (
                    "incoming",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this domain can receive email.",
                        verbose_name="incoming",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Owner of this domain, null for system domains.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DkimKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("rsa2048", "RSA 2048"),
                            ("rsa1024", "RSA 1024"),
                            ("ed25519", "Ed25519"),
                        ],
                        help_text="Cryptographic algorithm and size for this DKIM key.",
                        max_length=8,
                        verbose_name="key type",
                    ),
                ),
                (
                    "private_key",
                    models.TextField(
                        help_text="PEM-encoded private key used for DKIM signing.",
                        verbose_name="private key",
                    ),
                ),
                (
                    "selector",
                    models.CharField(
                        help_text="DKIM selector string used in the DNS record name.",
                        max_length=6,
                        verbose_name="selector",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active keys are used for signing and served in DNS.",
                        verbose_name="active",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dkim_keys",
                        to="domains.domain",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "selector"),
                        name="unique_dkim_selector_per_domain",
                    )
                ],
            },
        ),
    ]
