# Generated by Django 6.1rc1 on 2026-08-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="org",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="accounts.organization",
            ),
        ),
    ]
