# Generated by Django 6.1 on 2026-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="mx_error",
            field=models.TextField(
                blank=True,
                help_text="Failure detail if the MX record is incorrect.",
                verbose_name="MX error",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="mx_status",
            field=models.TextField(
                choices=[
                    ("ok", "ok"),
                    ("error", "error"),
                    ("pending", "pending"),
                    ("unchecked", "unchecked"),
                ],
                default="unchecked",
                help_text="MX record check result on the root domain.",
                verbose_name="MX status",
            ),
        ),
    ]
