# Generated by Django 6.1rc1 on 2026-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="reputation_hold",
            field=models.BooleanField(
                default=False,
                help_text="Suspended domains cannot send outgoing messages.",
                verbose_name="reputation hold",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="reputation_hold_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the reputation hold was applied.",
                null=True,
                verbose_name="reputation hold at",
            ),
        ),
    ]
