# Generated by Django 6.0.6 on 2026-07-27 19:32

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("domains", "0001_initial"),
        ("kms", "0003_alter_signingkey_encrypted_private_key"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(
                django.db.models.functions.text.Lower("name"),
                name="domain_name_lower_idx",
            ),
        ),
    ]
