# Generated by Django 6.1 on 2026-08-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_organization_suspended_at"),
        ("domains", "0001_initial"),
        ("kms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="is_platform",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Whether this domain is the platform identity that cosigns outgoing mail; at most one domain carries the flag, and its name equals RELAY_PLATFORM_DOMAIN.",
                verbose_name="platform",
            ),
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_platform", True)),
                fields=("is_platform",),
                name="unique_platform_domain",
            ),
        ),
    ]
