# Generated by Django 6.1rc1 on 2026-08-03 19:25

from django.db import migrations
from django.utils import timezone


def create_managed_domains(apps, schema_editor):
    """Create a relay-managed subdomain for each existing organization."""
    Organization = apps.get_model("accounts", "Organization")
    Domain = apps.get_model("domains", "Domain")

    from django.conf import settings as django_settings

    now = timezone.now()
    for org in Organization.objects.all():
        name = f"{org.slug}.{django_settings.RELAY_FREE_SENDER_DOMAIN}"
        Domain.objects.get_or_create(
            name=name,
            defaults={
                "org": org,
                "verified_at": now,
                "nameserver_status": "ok",
                "spf_status": "ok",
                "dkim_status": "ok",
                "dmarc_status": "ok",
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_managed_domains, migrations.RunPython.noop),
    ]
