# Generated by Django 6.0.5 on 2026-07-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="ns_error",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="ns_status",
        ),
        migrations.AddField(
            model_name="domain",
            name="nameserver_error",
            field=models.TextField(
                blank=True,
                help_text="Error message if nameserver verification failed.",
                verbose_name="nameserver error",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="nameserver_status",
            field=models.CharField(
                choices=[
                    ("ok", "ok"),
                    ("error", "error"),
                    ("pending", "pending"),
                    ("unchecked", "unchecked"),
                ],
                default="unchecked",
                help_text="Status of nameserver delegation verification.",
                max_length=9,
                verbose_name="nameserver status",
            ),
        ),
    ]
