# Generated by Django 6.1rc1 on 2026-08-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="dkim_status",
            field=models.TextField(
                choices=[
                    ("ok", "ok"),
                    ("error", "error"),
                    ("pending", "pending"),
                    ("unchecked", "unchecked"),
                ],
                default="unchecked",
                help_text="DKIM CNAME check result on the root domain.",
                verbose_name="DKIM status",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="dmarc_status",
            field=models.TextField(
                choices=[
                    ("ok", "ok"),
                    ("error", "error"),
                    ("pending", "pending"),
                    ("unchecked", "unchecked"),
                ],
                default="unchecked",
                help_text="DMARC record check result on the root domain.",
                verbose_name="DMARC status",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="nameserver_status",
            field=models.TextField(
                choices=[
                    ("ok", "ok"),
                    ("error", "error"),
                    ("pending", "pending"),
                    ("unchecked", "unchecked"),
                ],
                default="unchecked",
                help_text="NS delegation check result for the sender subdomain.",
                verbose_name="nameserver status",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="spf_status",
            field=models.TextField(
                choices=[
                    ("ok", "ok"),
                    ("error", "error"),
                    ("pending", "pending"),
                    ("unchecked", "unchecked"),
                ],
                default="unchecked",
                help_text="SPF record check result on the root domain.",
                verbose_name="SPF status",
            ),
        ),
    ]
