# Generated by Django 6.1rc1 on 2026-08-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0002_alter_domain_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="apex_ns_delegated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the apex domain NS records are delegated to our nameservers.",
                verbose_name="apex NS delegated",
            ),
        ),
    ]
