# Generated by Django 6.1 on 2026-08-30 19:21

from django.db import migrations


def purge_rsa1024_signing_keys(apps, schema_editor):
    """
    Delete now-unused RSA-1024 signing keys.

    Runs after the field removal, so no foreign key protects the rows
    anymore. The keys cannot sign outgoing mail from here on.
    """
    SigningKey = apps.get_model("kms", "SigningKey")
    SigningKey.objects.filter(algorithm="rsa-1024").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0002_domain_mx_error_domain_mx_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="dkim_key_rsa1024",
        ),
        migrations.RunPython(
            purge_rsa1024_signing_keys,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
