# Generated by Django 6.0.5 on 2026-07-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmtpCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        editable=False,
                        help_text="Hashed key — plaintext is shown only once at creation.",
                        max_length=128,
                        verbose_name="key hash",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        editable=False,
                        help_text="First 8 characters for display and lookup.",
                        max_length=8,
                        verbose_name="key prefix",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label for this credential.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this key was last used for authentication.",
                        null=True,
                        verbose_name="last used",
                    ),
                ),
                (
                    "hold",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this key is suspended and cannot be used.",
                        verbose_name="hold",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("smtp", "SMTP"), ("smtp-ip", "SMTP-IP")],
                        default="smtp",
                        help_text="SMTP authentication method.",
                        max_length=7,
                        verbose_name="type",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
