# Generated by Django 6.0.5 on 2026-07-19 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("domains", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmtpCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        editable=False,
                        help_text="Hashed key — plaintext is shown only once at creation.",
                        max_length=128,
                        verbose_name="key hash",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        editable=False,
                        help_text="First 8 characters for display and lookup.",
                        max_length=8,
                        verbose_name="key prefix",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label for this credential.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this key was last used for authentication.",
                        null=True,
                        verbose_name="last used",
                    ),
                ),
                (
                    "hold",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this key is suspended and cannot be used.",
                        verbose_name="hold",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("smtp", "SMTP"), ("smtp-ip", "SMTP-IP")],
                        default="smtp",
                        help_text="SMTP authentication method.",
                        max_length=7,
                        verbose_name="type",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization that owns this resource; null for system objects.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutgoingMessage",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rcpt_to",
                    models.TextField(
                        help_text="Recipient email address(es).", verbose_name="to"
                    ),
                ),
                (
                    "mail_from",
                    models.EmailField(
                        help_text="Sender email address.",
                        max_length=254,
                        verbose_name="from",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        blank=True,
                        help_text="Email subject line.",
                        verbose_name="subject",
                    ),
                ),
                (
                    "message_id",
                    models.TextField(
                        blank=True,
                        help_text="SMTP Message-ID header value.",
                        verbose_name="message ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this message was received by the SMTP server.",
                        verbose_name="received at",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("sent", "sent"),
                            ("delivered", "delivered"),
                            ("held", "held"),
                            ("bounced", "bounced"),
                            ("dropped", "dropped"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        help_text="Current delivery status of this message.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "received_with_ssl",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message was received over a TLS connection.",
                        verbose_name="received with SSL",
                    ),
                ),
                (
                    "raw_body",
                    models.FileField(
                        blank=True,
                        help_text="Raw .eml file for this message.",
                        upload_to="mail/",
                        verbose_name="raw body",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_messages",
                        to="domains.domain",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_messages",
                        to="smtp.smtpcredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "sent"),
                            ("delivered", "delivered"),
                            ("failed", "failed"),
                            ("retry", "retry"),
                            ("bounced", "bounced"),
                        ],
                        help_text="Transmission status for this attempt.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="SMTP response code from the remote server.",
                        null=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        help_text="Raw SMTP output from the remote server.",
                        verbose_name="output",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable transmission details.",
                        verbose_name="details",
                    ),
                ),
                (
                    "sent_with_ssl",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this transmission was sent over TLS.",
                        verbose_name="sent with SSL",
                    ),
                ),
                (
                    "log_id",
                    models.CharField(
                        blank=True,
                        help_text="Remote server log ID for this transmission.",
                        max_length=255,
                        verbose_name="log ID",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmissions",
                        to="smtp.outgoingmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="outgoingmessage",
            index=models.Index(
                fields=["sender", "status"], name="smtp_outgoi_sender__cd0335_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outgoingmessage",
            index=models.Index(
                fields=["sender", "received_at"], name="smtp_outgoi_sender__636183_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outgoingmessage",
            index=models.Index(
                fields=["domain", "status"], name="smtp_outgoi_domain__f5c5d1_idx"
            ),
        ),
    ]
