# Generated by Django 6.0.6 on 2026-07-28 17:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("domains", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmtpCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        editable=False,
                        help_text="Hashed key — plaintext is shown only once at creation.",
                        max_length=128,
                        verbose_name="key hash",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        editable=False,
                        help_text="First 8 characters, for display and O(1) lookup.",
                        max_length=8,
                        verbose_name="key prefix",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful verification.",
                        null=True,
                        verbose_name="last used",
                    ),
                ),
                (
                    "hold",
                    models.BooleanField(
                        default=False,
                        help_text="Suspended keys cannot be used.",
                        verbose_name="hold",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("smtp", "SMTP"), ("smtp-ip", "SMTP-IP")],
                        default="smtp",
                        help_text="SMTP authentication method.",
                        max_length=7,
                        verbose_name="type",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutgoingMessage",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "mail_from",
                    models.EmailField(
                        help_text="Envelope sender address (MAIL FROM).",
                        max_length=254,
                        verbose_name="mail from",
                    ),
                ),
                (
                    "rcpt_to",
                    models.TextField(
                        help_text="Envelope recipient address(es) (RCPT TO).",
                        verbose_name="rcpt to",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        blank=True,
                        help_text="RFC 5322 Subject header value.",
                        verbose_name="subject",
                    ),
                ),
                (
                    "message_id",
                    models.TextField(
                        blank=True,
                        help_text="RFC 5322 Message-ID header.",
                        verbose_name="message ID",
                    ),
                ),
                (
                    "raw_body",
                    models.FileField(
                        blank=True,
                        help_text="Raw RFC 822 message bytes.",
                        upload_to="messages/",
                        verbose_name="raw body",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the message was accepted.",
                        verbose_name="received at",
                    ),
                ),
                (
                    "received_with_tls",
                    models.BooleanField(
                        default=False,
                        help_text="Submission received over TLS.",
                        verbose_name="received with TLS",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("sent", "sent"),
                            ("delivered", "delivered"),
                            ("held", "held"),
                            ("bounced", "bounced"),
                            ("dropped", "dropped"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        help_text="Send/deliver lifecycle state.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_messages",
                        to="domains.domain",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_messages",
                        to="accounts.organization",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_messages",
                        to="smtp.smtpcredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "sent"),
                            ("delivered", "delivered"),
                            ("failed", "failed"),
                            ("retry", "retry"),
                            ("bounced", "bounced"),
                        ],
                        help_text="Outcome of this delivery attempt.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="SMTP response code from the remote server.",
                        null=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        help_text="Raw SMTP transcript from the remote server.",
                        verbose_name="output",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable explanation of the outcome.",
                        verbose_name="details",
                    ),
                ),
                (
                    "sent_with_ssl",
                    models.BooleanField(
                        default=False,
                        help_text="Delivered over TLS.",
                        verbose_name="sent with SSL",
                    ),
                ),
                (
                    "log_id",
                    models.CharField(
                        blank=True,
                        help_text="Remote server log identifier.",
                        max_length=255,
                        verbose_name="log ID",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmissions",
                        to="smtp.outgoingmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="outgoingmessage",
            index=models.Index(
                fields=["sender", "status"], name="smtp_outgoi_sender__cd0335_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outgoingmessage",
            index=models.Index(
                fields=["sender", "received_at"], name="smtp_outgoi_sender__636183_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outgoingmessage",
            index=models.Index(
                fields=["domain", "status"], name="smtp_outgoi_domain__f5c5d1_idx"
            ),
        ),
    ]
