# Generated by Django 6.1.1 on 2026-09-15 17:11

import django.db.models.deletion
from django.db import migrations, models

import services.email.msa.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MsaCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        editable=False,
                        help_text="Hashed key. The plaintext appears only once at creation.",
                        max_length=128,
                        verbose_name="key hash",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        editable=False,
                        help_text="First 8 characters, for display and O(1) lookup.",
                        max_length=8,
                        verbose_name="key prefix",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful verification.",
                        null=True,
                        verbose_name="last used",
                    ),
                ),
                (
                    "hold",
                    models.BooleanField(
                        default=False,
                        help_text="Suspended keys cannot be used.",
                        verbose_name="hold",
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[("smtp", "SMTP"), ("smtp-ip", "SMTP-IP")],
                        default="smtp",
                        help_text="SMTP authentication method.",
                        verbose_name="type",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutgoingMessage",
            fields=[
                (
                    "message_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="message.message",
                    ),
                ),
                (
                    "feedback_id",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Feedback-ID header relay minted for this message. Providers echo it in FBL complaints, proving per-message identity when they do not echo the VERP envelope sender.",
                        verbose_name="Feedback-ID",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_messages",
                        to="msa.msacredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
            bases=("message.message",),
        ),
        migrations.CreateModel(
            name="SuppressionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "address_hash",
                    services.email.msa.models.HashedEmailField(
                        help_text="Salted SHA-256 of the lowercased email address.",
                        verbose_name="address hash",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        choices=[("bounce", "bounce"), ("manual", "manual")],
                        default="manual",
                        help_text="How the entry was added.",
                        verbose_name="reason",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "address_hash"),
                        name="unique_suppression_per_org",
                    )
                ],
            },
        ),
    ]
