# Generated by Django 6.1.1 on 2026-09-17 11:55

from django.db import migrations, models
from django.db.models.functions import Substr


def trim_key_prefix(apps, schema_editor):
    """Trim stored key prefixes to the shortened lookup length."""
    credential = apps.get_model("msa", "MsaCredential")
    credential.objects.update(key_prefix=Substr("key_prefix", 1, 4))


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0001_initial"),
    ]

    operations = [
        # Trim first, or rows with longer prefixes fail the column change.
        migrations.RunPython(trim_key_prefix, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="msacredential",
            name="key_prefix",
            field=models.CharField(
                editable=False,
                help_text="First 4 characters, for display and O(1) lookup.",
                max_length=4,
                verbose_name="key prefix",
            ),
        ),
    ]
