# Generated by Django 6.1 on 2026-08-03 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("msa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuppressionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "address_hash",
                    models.TextField(
                        help_text="Salted SHA-256 of the lowercased email address.",
                        verbose_name="address hash",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        choices=[("bounce", "bounce"), ("manual", "manual")],
                        default="manual",
                        help_text="How the entry was added.",
                        verbose_name="reason",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "address_hash"),
                        name="unique_suppression_per_org",
                    )
                ],
            },
        ),
    ]
