# Generated by Django 6.1.1 on 2026-09-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0002_alter_msacredential_key_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msacredential",
            name="type",
            field=models.TextField(
                choices=[
                    ("smtp", "SMTP"),
                    ("smtp-ip", "SMTP-IP"),
                    ("sandbox", "Sandbox"),
                ],
                default="smtp",
                help_text="Purpose of the credential. Sandbox credentials accept submissions without a delivery attempt.",
                verbose_name="type",
            ),
        ),
    ]
