# Generated by Django 6.1 on 2026-08-23 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0003_alter_suppressionentry_address_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outgoingmessage",
            name="sender",
        ),
    ]
