# Generated by Django 6.1 on 2026-08-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0004_remove_outgoingmessage_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoingmessage",
            name="feedback_id",
            field=models.TextField(
                blank=True,
                db_index=True,
                default="",
                help_text="Feedback-ID header relay minted for this message. Providers echo it in FBL complaints, proving per-message identity when they do not echo the VERP envelope sender.",
                verbose_name="Feedback-ID",
            ),
        ),
    ]
