# Generated by Django 6.1 on 2026-08-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0006_transmission_tls_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmission",
            name="receiving_mx_ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the MX that handled this delivery attempt.",
                null=True,
                verbose_name="receiving MX IP address",
            ),
        ),
        migrations.AddField(
            model_name="transmission",
            name="sending_mta_ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address relay sent this delivery attempt from.",
                null=True,
                verbose_name="sending MTA IP address",
            ),
        ),
    ]
