# Generated by Django 6.1 on 2026-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0007_transmission_receiving_mx_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transmission",
            name="status",
            field=models.TextField(
                choices=[
                    ("submitted", "submitted"),
                    ("sent", "sent"),
                    ("failed", "failed"),
                    ("retry", "retry"),
                    ("bounced", "bounced"),
                ],
                help_text="Outcome of this delivery attempt.",
                verbose_name="status",
            ),
        ),
    ]
