# Generated by Django 6.1.1 on 2026-09-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0008_alter_transmission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmission",
            name="submission_ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address that submitted this message to relay's MSA.",
                null=True,
                verbose_name="submission IP address",
            ),
        ),
    ]
