# Generated by Django 6.1.1 on 2026-09-08 09:21

from django.db import migrations, models


def backfill_transmission_times(apps, schema_editor):
    """Backfill legacy transmission times with the record creation time."""
    transmission = apps.get_model("msa", "transmission")
    transmission.objects.filter(started_at__isnull=True).update(
        started_at=models.F("created_at"),
        finished_at=models.F("created_at"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0009_transmission_submission_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmission",
            name="finished_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this transmission leg ended.",
                null=True,
                verbose_name="finished",
            ),
        ),
        migrations.AddField(
            model_name="transmission",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this transmission leg started.",
                null=True,
                verbose_name="started",
            ),
        ),
        migrations.RunPython(backfill_transmission_times, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="transmission",
            name="finished_at",
            field=models.DateTimeField(
                help_text="When this transmission leg ended.", verbose_name="finished"
            ),
        ),
        migrations.AlterField(
            model_name="transmission",
            name="started_at",
            field=models.DateTimeField(
                help_text="When this transmission leg started.", verbose_name="started"
            ),
        ),
    ]
