# Generated by Django 6.1.1 on 2026-09-09 20:31

from django.db import migrations


def copy_transmissions(apps, schema_editor):
    """Move the transmission rows into the message app's table."""
    old_model = apps.get_model("msa", "transmission")
    new_model = apps.get_model("message", "transmission")
    fields = (
        "id",
        "modified_at",
        "created_at",
        "started_at",
        "finished_at",
        "mx_host",
        "status",
        "code",
        "output",
        "details",
        "tls_mode",
        "tls_version",
        "tls_cipher",
        "tls_certificate_id",
        "message_id",
        "sending_mta_ip_address",
        "receiving_mx_ip_address",
        "submission_ip_address",
    )
    for row in old_model.objects.values(*fields):
        row["remote_host"] = row.pop("mx_host")
        row["local_ip_address"] = row.pop("sending_mta_ip_address")
        row["remote_ip_address"] = row.pop("receiving_mx_ip_address") or row.pop(
            "submission_ip_address"
        )
        new_model.objects.create(**row)


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0008_remove_message_received_with_tls_and_more"),
        ("msa", "0010_transmission_finished_at_transmission_started_at"),
    ]

    operations = [
        migrations.RunPython(copy_transmissions, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="Transmission",
        ),
    ]
