# Generated by Django 6.1.1 on 2026-09-09 14:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0010_transmission_finished_at_transmission_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transmission",
            name="finished_at",
            field=models.DateTimeField(
                db_index=True,
                help_text="When the timing finished.",
                verbose_name="finished",
            ),
        ),
        migrations.AlterField(
            model_name="transmission",
            name="started_at",
            field=models.DateTimeField(
                db_index=True,
                help_text="When the timing started.",
                verbose_name="started",
            ),
        ),
        migrations.CreateModel(
            name="SpamCheck",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing started.",
                        verbose_name="started",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the timing finished.",
                        verbose_name="finished",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="rspamd score the check returned, or null when the check failed.",
                        null=True,
                        verbose_name="score",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spam_checks",
                        to="msa.outgoingmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "spam check",
                "ordering": ["started_at", "created_at"],
                "abstract": False,
            },
        ),
    ]
