# Generated by Django 6.1.1 on 2026-09-08 15:04

import django.db.models.deletion
from django.db import migrations, models


def create_transmission_timings(apps, schema_editor):
    """Backfill timing parents for the legacy transmission rows."""
    timing = apps.get_model("message", "timing")
    transmission = apps.get_model("msa", "transmission")
    for row in transmission.objects.all():
        timing.objects.bulk_create(
            [
                timing(
                    pk=row.pk,
                    message_id=row.message_id,
                    started_at=row.started_at,
                    finished_at=row.finished_at,
                )
            ]
        )
        # bulk_create cannot override the auto timestamps of TimeStamped.
        timing.objects.filter(pk=row.pk).update(
            created_at=row.created_at,
            modified_at=row.modified_at,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0008_timing"),
        ("msa", "0010_transmission_finished_at_transmission_started_at"),
    ]

    operations = [
        migrations.RunPython(create_transmission_timings, migrations.RunPython.noop),
        # The legacy `id` column becomes the parent link, keeping its values.
        # The state first declares the link without a database constraint so
        # the following AlterField emits the constraint on every backend.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE msa_transmission RENAME COLUMN id TO timing_ptr_id;",
                    reverse_sql="ALTER TABLE msa_transmission RENAME COLUMN timing_ptr_id TO id;",
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name="transmission", name="id"),
                migrations.AddField(
                    model_name="transmission",
                    name="timing_ptr",
                    field=models.OneToOneField(
                        auto_created=True,
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="message.timing",
                    ),
                ),
            ],
        ),
        # Materialize the parent-link constraint at the database level.
        migrations.AlterField(
            model_name="transmission",
            name="timing_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="message.timing",
            ),
        ),
        migrations.RemoveField(model_name="transmission", name="message"),
        migrations.RemoveField(model_name="transmission", name="started_at"),
        migrations.RemoveField(model_name="transmission", name="finished_at"),
        migrations.RemoveField(model_name="transmission", name="created_at"),
        migrations.RemoveField(model_name="transmission", name="modified_at"),
    ]
