# Generated by Django 6.1.1 on 2026-09-08 22:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0010_transmission_finished_at_transmission_started_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpamCheck",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="When the spam check started.", verbose_name="started"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        help_text="When the spam check finished.",
                        verbose_name="finished",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="rspamd score the check returned.",
                        null=True,
                        verbose_name="score",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spam_checks",
                        to="msa.outgoingmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "spam check",
                "ordering": ["started_at", "created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["message", "started_at"],
                        name="msa_spamche_message_c1426b_idx",
                    )
                ],
            },
        ),
    ]
