# Generated by Django 6.1.1 on 2026-09-09 14:18

from django.db import migrations


def copy_transmissions(apps, schema_editor):
    """Move the transmission rows into the message app's table."""
    old_model = apps.get_model("msa", "transmission")
    new_model = apps.get_model("message", "transmission")
    fields = (
        "id",
        "modified_at",
        "created_at",
        "started_at",
        "finished_at",
        "mx_host",
        "sending_mta_ip_address",
        "receiving_mx_ip_address",
        "submission_ip_address",
        "status",
        "code",
        "output",
        "details",
        "tls_mode",
        "tls_version",
        "tls_cipher",
        "tls_certificate_id",
        "log_id",
        "message_id",
    )
    for row in old_model.objects.values(*fields):
        new_model.objects.create(**row)


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0008_transmission"),
        ("msa", "0011_alter_transmission_finished_at_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_transmissions, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="Transmission",
        ),
    ]
