# Generated by Django 6.1.1 on 2026-09-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msa", "0011_spamcheck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spamcheck",
            name="finished_at",
            field=models.DateTimeField(
                help_text="When the timing finished.", verbose_name="finished"
            ),
        ),
        migrations.AlterField(
            model_name="spamcheck",
            name="started_at",
            field=models.DateTimeField(
                help_text="When the timing started.", verbose_name="started"
            ),
        ),
        migrations.AlterField(
            model_name="transmission",
            name="finished_at",
            field=models.DateTimeField(
                help_text="When the timing finished.", verbose_name="finished"
            ),
        ),
        migrations.AlterField(
            model_name="transmission",
            name="started_at",
            field=models.DateTimeField(
                help_text="When the timing started.", verbose_name="started"
            ),
        ),
    ]
