"""
Django settings for demo project.

Generated by 'django-admin startproject'.

For more information on this file, see
https://docs.djangoproject.com/en/stable/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/stable/ref/settings/
"""

import base64
import hashlib
import os
from pathlib import Path

import environ
from cryptography.fernet import Fernet

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/stable/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-!@#$%^&*()_+")

# Fernet instance for symmetric encryption of secrets at rest (e.g. webhook
# signing keys). Keyed off SECRET_KEY so a single key rotation invalidates
# all ciphertexts. Migrate to a hardware KMS (e.g. AWS KMS) in production.
FERNET = Fernet(base64.urlsafe_b64encode(hashlib.sha256(SECRET_KEY.encode()).digest()))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

# True when running under pytest (see pyproject.toml TEST env var).
TEST = env.bool("TEST", default=False)

ALLOWED_HOSTS = [
    h.strip()
    for h in env.list(
        "ALLOWED_HOSTS", default=[] if DEBUG else [env("HOSTNAME", default="localhost")]
    )
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

# Render Django forms (and widgets) using the project's template engine,
# so per-project overrides under `templates/django/forms/...` take effect.
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

INSTALLED_APPS = [
    # First-party apps (abstract first so its widget overrides win)
    "abstract",
    "django.forms",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    # Third-party apps
    "health_check",
    "social_django",
    "storages",
    "rest_framework",
    "threadmill",
    # First-party apps
    "accounts",
    "kms",
    "domains",
    "legal",
    "know_how",
    "well_known",
    "root",
    "smtp",
    "tx_email",
    "mx",
    "dmarc",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "domains.middleware.MtaStsHostMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "root.urls"

_TEMPLATES_LOADERS = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "legal" / "docs",
            BASE_DIR / "know_how" / "docs",
        ],
        "OPTIONS": {
            "context_processors": (
                ["django.template.context_processors.debug"] if DEBUG else []
            )
            + [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.organizations",
            ],
            "debug": DEBUG,
            "loaders": (
                _TEMPLATES_LOADERS
                if DEBUG
                else [
                    (
                        "django.template.loaders.cached.Loader",
                        _TEMPLATES_LOADERS,
                    ),
                ]
            ),
        },
    },
]

WSGI_APPLICATION = "root.wsgi.application"


# Database
# https://docs.djangoproject.com/en/stable/ref/settings/#databases

DATABASES = {"default": env.db(default="sqlite:///db.sqlite3")}

# Caches
# https://docs.djangoproject.com/en/stable/ref/settings/#caches

CACHES = {"default": env.cache("REDIS_URL", default="locmemcache://")}


REDIS_URL = env("REDIS_URL", default="redis:///")


# Password validation
# https://docs.djangoproject.com/en/stable/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/stable/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Storages

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage"
        if env("AWS_STORAGE_BUCKET_NAME", default="")
        else "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# S3 / django-storages
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default="")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-east-1")
AWS_S3_ACCESS_KEY_ID = env("AWS_S3_ACCESS_KEY_ID", default="")
AWS_S3_SECRET_ACCESS_KEY = env("AWS_S3_SECRET_ACCESS_KEY", default="")
AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL", default="")
AWS_S3_ADDRESSING_STYLE = env("AWS_S3_ADDRESSING_STYLE", default="auto")
AWS_S3_MESSAGE_PREFIX = env("AWS_S3_MESSAGE_PREFIX", default="messages/")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/stable/howto/static-files/

STATIC_URL = "static/"
MEDIA_ROOT = BASE_DIR / "storage"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Relay config

RELAY_PLATFORM_DOMAIN = env(
    "RELAY_PLATFORM_DOMAIN", default=env("HOSTNAME", default="localhost")
)

RELAY_SENDER_SUBDOMAIN_PREFIX = env(
    "RELAY_SENDER_SUBDOMAIN_PREFIX", default="mail.relay"
)

RELAY_DNS_NS_NAMESERVERS = [
    f"ns1.{RELAY_PLATFORM_DOMAIN}",
    f"ns2.{RELAY_PLATFORM_DOMAIN}",
]
RELAY_DNS_SMTP_IPS = [
    ip.strip() for ip in env.list("RELAY_DNS_SMTP_IPS", default=["127.0.0.1"])
]
RELAY_DNS_SPF_INCLUDE = f"spf.{RELAY_PLATFORM_DOMAIN}"
RELAY_DNS_RETURN_PATH_DOMAIN = f"rp.{RELAY_PLATFORM_DOMAIN}"
RELAY_DNS_DKIM_IDENTIFIER = env("RELAY_DNS_DKIM_IDENTIFIER", default="relay")
RELAY_DNS_CUSTOM_RETURN_PATH_PREFIX = env(
    "RELAY_DNS_CUSTOM_RETURN_PATH_PREFIX", default="rp"
)
RELAY_DNS_DOMAIN_VERIFY_PREFIX = env(
    "RELAY_DNS_DOMAIN_VERIFY_PREFIX", default="relay-verification"
)

RELAY_FREE_SENDER_DOMAIN = env(
    "RELAY_FREE_SENDER_DOMAIN", default=f"open.{RELAY_PLATFORM_DOMAIN}"
)

RELAY_SMTP_HOST = env("RELAY_SMTP_HOST", default="smtp")
RELAY_SMTP_LISTEN_HOST = env("RELAY_SMTP_LISTEN_HOST", default="0.0.0.0")
RELAY_SMTP_LISTEN_PORT = env.int("RELAY_SMTP_LISTEN_PORT", default=587)
RELAY_SMTP_SUBMISSION_PORT = env.int("RELAY_SMTP_SUBMISSION_PORT", default=587)
RELAY_SMTP_MAX_MESSAGE_SIZE = env.int(
    "RELAY_SMTP_MAX_MESSAGE_SIZE", default=10485760
)  # 10 MB

RELAY_MX_LISTEN_HOST = env("RELAY_MX_LISTEN_HOST", default="0.0.0.0")
RELAY_MX_LISTEN_PORT = env.int("RELAY_MX_LISTEN_PORT", default=25)
RELAY_MX_MAX_MESSAGE_SIZE = env.int(
    "RELAY_MX_MAX_MESSAGE_SIZE", default=10485760
)  # 10 MB
RELAY_MX_TLS_CERT_PATH = env("RELAY_MX_TLS_CERT_PATH", default="")
RELAY_MX_TLS_KEY_PATH = env("RELAY_MX_TLS_KEY_PATH", default="")

RELAY_WEBHOOK_TIMEOUT = env.int("RELAY_WEBHOOK_TIMEOUT", default=30)

RELAY_DMARC_REPORT_LOCAL_PART = env("RELAY_DMARC_REPORT_LOCAL_PART", default="dmarc")
RELAY_DMARC_RUF_LOCAL_PART = env("RELAY_DMARC_RUF_LOCAL_PART", default="ruf")
RELAY_TLS_REPORT_LOCAL_PART = env("RELAY_TLS_REPORT_LOCAL_PART", default="tls")

RELAY_MTA_STS_MODE = env("RELAY_MTA_STS_MODE", default="enforce")
RELAY_MTA_STS_MAX_AGE = env.int("RELAY_MTA_STS_MAX_AGE", default=604800)
RELAY_MTA_STS_POLICY_ID = env("RELAY_MTA_STS_POLICY_ID", default="20260730T100000Z")

RELAY_DNS_LISTEN_HOST = env("RELAY_DNS_LISTEN_HOST", default="0.0.0.0")
RELAY_DNS_LISTEN_PORT = env.int("RELAY_DNS_LISTEN_PORT", default=53)


# Django task framework
# Production uses Threadmill with a Redis backend and a worker process.
# Tests use ImmediateRetryBackend, which runs tasks synchronously.
if TEST:
    TASKS = {
        "default": {
            "BACKEND": "root.backends.ImmediateRetryBackend",
        },
    }
else:
    TASKS = {
        "default": {
            "BACKEND": "threadmill.backends.redis.RedisTaskBackend",
            "REDIS_URL": REDIS_URL,
        },
    }

# Authentication
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:org-list"
LOGOUT_REDIRECT_URL = "home"

GITHUB_CLIENT_ID = env("GITHUB_CLIENT_ID", default="")
GITHUB_CLIENT_SECRET = env("GITHUB_CLIENT_SECRET", default="")

# python-social-auth
AUTHENTICATION_BACKENDS = [
    "social_core.backends.github.GithubOAuth2",
    "django.contrib.auth.backends.ModelBackend",
]

SOCIAL_AUTH_GITHUB_KEY = GITHUB_CLIENT_ID
SOCIAL_AUTH_GITHUB_SECRET = GITHUB_CLIENT_SECRET

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "accounts.pipelines.create_default_organization",
)

# Logging
# https://docs.djangoproject.com/en/stable/topics/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


# Error monitoring (Sentry)
if (SENTRY_DSN := env("SENTRY_DSN", default="").strip()) and not TEST and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.asyncio import AsyncioIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.threading import ThreadingIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=env("SENTRY_ENVIRONMENT", default="").strip() or "production",
        integrations=[
            DjangoIntegration(),
            AsyncioIntegration(),
            ThreadingIntegration(),
        ],
        send_default_pii=False,
        traces_sample_rate=float(
            env("SENTRY_TRACES_SAMPLE_RATE", default="").strip() or "0.0"
        ),
    )
