# Generated by Django 6.1rc1 on 2026-08-03 16:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mx", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DmarcFailureReport",
            fields=[
                (
                    "incomingmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "reporting_org",
                    models.TextField(
                        blank=True,
                        help_text="Organization that generated the report.",
                        verbose_name="reporting organization",
                    ),
                ),
                (
                    "reporting_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email from the report metadata.",
                        max_length=254,
                        verbose_name="reporting email",
                    ),
                ),
                (
                    "source_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Sending IP address.",
                        null=True,
                        verbose_name="source IP address",
                    ),
                ),
                (
                    "arrival_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the original message was received.",
                        null=True,
                        verbose_name="arrival at",
                    ),
                ),
                (
                    "original_mail_from",
                    models.EmailField(
                        blank=True,
                        help_text="Envelope sender of the original message.",
                        max_length=254,
                        verbose_name="original mail from",
                    ),
                ),
                (
                    "original_rcpt_to",
                    models.EmailField(
                        blank=True,
                        help_text="Envelope recipient of the original message.",
                        max_length=254,
                        verbose_name="original rcpt to",
                    ),
                ),
                (
                    "authentication_results",
                    models.TextField(
                        blank=True,
                        help_text="SPF and DKIM authentication results from the report.",
                        verbose_name="authentication results",
                    ),
                ),
                (
                    "delivery_result",
                    models.TextField(
                        choices=[
                            ("delivered", "delivered"),
                            ("spam", "spam"),
                            ("policy", "policy"),
                            ("rejected", "rejected"),
                            ("other", "other"),
                        ],
                        default="other",
                        help_text="What the reporting MTA did with the message.",
                        verbose_name="delivery result",
                    ),
                ),
                (
                    "original_headers",
                    models.TextField(
                        blank=True,
                        help_text="Headers of the original message from the report.",
                        verbose_name="original headers",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["arrival_at"], name="dmarc_dmarc_arrival_fddb87_idx"
                    )
                ],
            },
            bases=("mx.incomingmessage",),
        ),
        migrations.CreateModel(
            name="DmarcReport",
            fields=[
                (
                    "incomingmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "reporting_org",
                    models.TextField(
                        blank=True,
                        help_text="Organization that generated the report (from XML metadata).",
                        verbose_name="reporting organization",
                    ),
                ),
                (
                    "reporting_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email from the report metadata.",
                        max_length=254,
                        verbose_name="reporting email",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(
                        help_text="Unique report identifier from the reporting organization.",
                        verbose_name="report ID",
                    ),
                ),
                (
                    "begin_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the report period.",
                        null=True,
                        verbose_name="begin at",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the report period.",
                        null=True,
                        verbose_name="end at",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["begin_at"], name="dmarc_dmarc_begin_a_36db5a_idx"
                    )
                ],
            },
            bases=("mx.incomingmessage",),
        ),
        migrations.CreateModel(
            name="DmarcRecord",
            fields=[
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_ip_address",
                    models.GenericIPAddressField(
                        help_text="Sending IP address.",
                        verbose_name="source IP address",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of messages from this source IP.",
                        verbose_name="count",
                    ),
                ),
                (
                    "disposition",
                    models.TextField(
                        choices=[
                            ("none", "none"),
                            ("quarantine", "quarantine"),
                            ("reject", "reject"),
                        ],
                        help_text="DMARC policy outcome for this source.",
                        verbose_name="disposition",
                    ),
                ),
                (
                    "dkim_alignment",
                    models.TextField(
                        choices=[("pass", "pass"), ("fail", "fail")],
                        help_text="DKIM alignment result.",
                        verbose_name="DKIM alignment",
                    ),
                ),
                (
                    "spf_alignment",
                    models.TextField(
                        choices=[("pass", "pass"), ("fail", "fail")],
                        help_text="SPF alignment result.",
                        verbose_name="SPF alignment",
                    ),
                ),
                (
                    "header_from",
                    models.TextField(
                        blank=True,
                        help_text="From header domain.",
                        verbose_name="header from",
                    ),
                ),
                (
                    "envelope_from",
                    models.TextField(
                        blank=True,
                        help_text="Envelope sender domain (MAIL FROM).",
                        verbose_name="envelope from",
                    ),
                ),
                (
                    "dkim_domain",
                    models.TextField(
                        blank=True,
                        help_text="DKIM signing domain.",
                        verbose_name="DKIM domain",
                    ),
                ),
                (
                    "dkim_result",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("pass", "pass"),
                            ("fail", "fail"),
                            ("neutral", "neutral"),
                            ("none", "none"),
                            ("permerror", "permerror"),
                            ("temperror", "temperror"),
                        ],
                        help_text="DKIM authentication result.",
                        verbose_name="DKIM result",
                    ),
                ),
                (
                    "spf_domain",
                    models.TextField(
                        blank=True,
                        help_text="SPF checked domain.",
                        verbose_name="SPF domain",
                    ),
                ),
                (
                    "spf_result",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("pass", "pass"),
                            ("fail", "fail"),
                            ("neutral", "neutral"),
                            ("none", "none"),
                            ("permerror", "permerror"),
                            ("temperror", "temperror"),
                        ],
                        help_text="SPF authentication result.",
                        verbose_name="SPF result",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="dmarc.dmarcreport",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["report", "source_ip_address"],
                        name="dmarc_dmarc_report__5eff9a_idx",
                    )
                ],
            },
        ),
    ]
