# Generated by Django 6.1rc1 on 2026-08-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reputation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fblreport",
            name="feedback_type",
            field=models.TextField(
                choices=[
                    ("abuse", "abuse"),
                    ("fraud", "fraud"),
                    ("virus", "virus"),
                    ("not-spam", "not-spam"),
                    ("opt-out", "opt-out"),
                    ("other", "other"),
                ],
                default="abuse",
                help_text="ARF feedback type indicating the nature of the complaint.",
                verbose_name="feedback type",
            ),
        ),
    ]
