# Generated by Django 6.1 on 2026-08-28 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reputation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fblreport",
            options={"ordering": ["-created_at"]},
        ),
    ]
