# Generated by Django 6.1 on 2026-08-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reputation", "0002_alter_fblreport_feedback_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="fblreport",
            name="source",
            field=models.TextField(
                choices=[("provider", "provider"), ("relay", "relay")],
                default="provider",
                help_text="Provider reports were received from a mailbox provider and count as complaints. Relay-generated reports are records of spam Relay detected itself and are for visibility only.",
                verbose_name="source",
            ),
        ),
    ]
