# Generated by Django 6.1 on 2026-08-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0001_initial"),
        ("reputation", "0002_alter_fblreport_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fblreport",
            name="domain",
            field=models.ForeignKey(
                help_text="Domain the report is about.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="domains.domain",
            ),
        ),
    ]
