"""Contact-timeline link tags and email syntax highlighting.

The link tags are inclusion tags so the HTML lives in templates
(see ``tx_mail/templates/tx_mail/``) rather than in Python strings.
``highlight_email`` remains a simple filter because its output is
generated by Pygments, not by template markup.
"""

import re
import urllib.parse
from typing import NamedTuple

from django import template
from django.urls import reverse
from django.utils.safestring import mark_safe
from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers.email import EmailLexer

register = template.Library()

# Match entities that should become links inside an RFC 5322 header value.
# Email first (so the local@host form is not split into a domain-only link),
# then domains, then IPv4, then bracketed-IPv6 (which appears in `Received`
# and `Authentication-Results` headers).
_EMAIL_RE = re.compile(r"[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}")
_DOMAIN_RE = re.compile(
    r"\b(?:[A-Za-z0-9](?:[A-Za-z0-9\-]{0,61}[A-Za-z0-9])?\.)+"
    r"[A-Za-z]{2,63}\b"
)
_IPV4_RE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
_BRACKETED_IPV6_RE = re.compile(r"\[([0-9A-Fa-f:]+)\]")


def _contact_url(view: str, org_slug: str, params: dict[str, str]) -> str:
    """Return the merged-view URL with the given query parameters."""
    base = reverse(view, kwargs={"org_slug": org_slug})
    return f"{base}?{urllib.parse.urlencode(params)}"


def _org_slug(org) -> str:
    return org if isinstance(org, str) else org.slug


@register.inclusion_tag("tx_mail/link.html")
def email_link(value: str, org) -> dict:
    """Turn a single email address into a link to the contact-timeline messages view."""
    if not value:
        return {"url": "", "value": ""}
    return {
        "url": _contact_url(
            "tx_mail:contact-messages", _org_slug(org), {"email": value}
        ),
        "value": value,
    }


@register.inclusion_tag("tx_mail/email_links.html")
def email_links(value: str, org) -> dict:
    """Turn a comma-separated email field into one link per address."""
    if not value:
        return {"addresses": [], "org_slug": _org_slug(org)}
    addresses = [addr.strip() for addr in value.split(",") if addr.strip()]
    return {"addresses": addresses, "org_slug": _org_slug(org)}


@register.inclusion_tag("tx_mail/link.html")
def domain_link(value: str, org) -> dict:
    """Turn a domain name into a link to the contact-timeline messages view."""
    if not value:
        return {"url": "", "value": ""}
    return {
        "url": _contact_url(
            "tx_mail:contact-messages", _org_slug(org), {"domain": value}
        ),
        "value": value,
    }


@register.inclusion_tag("tx_mail/link.html")
def ip_link(value: str, org) -> dict:
    """Turn an IPv4 or IPv6 address into a link to the contact-timeline reports view."""
    if not value:
        return {"url": "", "value": ""}
    return {
        "url": _contact_url("tx_mail:contact-reports", _org_slug(org), {"ip": value}),
        "value": value,
    }


class _Hit(NamedTuple):
    start: int
    end: int
    kind: str
    text: str


def _entity_spans(value: str, org_slug: str) -> list[dict]:
    """Parse ``value`` into a list of span dicts for the header_value template.

    Each dict has ``text`` (the substring) and, for entities that should be
    links, ``url`` (the contact-timeline URL).  Non-link spans have
    ``url=None`` so the template can distinguish them.
    """
    hits: list[_Hit] = []

    for m in _EMAIL_RE.finditer(value):
        hits.append(_Hit(m.start(), m.end(), "email", m.group(0)))
    for m in _DOMAIN_RE.finditer(value):
        if any(h.start <= m.start() and m.end() <= h.end for h in hits):
            continue
        hits.append(_Hit(m.start(), m.end(), "domain", m.group(0)))
    for m in _IPV4_RE.finditer(value):
        if any(h.start <= m.start() and m.end() <= h.end for h in hits):
            continue
        hits.append(_Hit(m.start(), m.end(), "ipv4", m.group(0)))
    for m in _BRACKETED_IPV6_RE.finditer(value):
        if any(h.start <= m.start() and m.end() <= h.end for h in hits):
            continue
        hits.append(_Hit(m.start() + 1, m.end() - 1, "ip", m.group(1)))

    hits.sort(key=lambda h: (h.start, h.end))
    deduped: list[_Hit] = []
    last_end = -1
    for h in hits:
        if h.start < last_end:
            continue
        deduped.append(h)
        last_end = h.end

    spans: list[dict] = []
    cursor = 0
    for h in deduped:
        if cursor < h.start:
            spans.append({"text": value[cursor : h.start], "url": None})
        if h.kind == "email":
            url = _contact_url("tx_mail:contact-messages", org_slug, {"email": h.text})
        elif h.kind == "domain":
            url = _contact_url("tx_mail:contact-messages", org_slug, {"domain": h.text})
        else:
            url = _contact_url("tx_mail:contact-reports", org_slug, {"ip": h.text})
        spans.append({"text": h.text, "url": url})
        cursor = h.end
    if cursor < len(value):
        spans.append({"text": value[cursor:], "url": None})
    return spans


@register.inclusion_tag("tx_mail/header_value.html")
def header_value(value: str, org) -> dict:
    """Render an RFC 5322 header value with every entity turned into a link."""
    if not value:
        return {"spans": []}
    return {"spans": _entity_spans(value, _org_slug(org))}


_email_formatter = HtmlFormatter(cssclass="highlight-email")


@register.filter
def highlight_email(value: str) -> str:
    """Render a raw RFC 822 message with Pygments' :class:`EmailLexer`.

    The output is HTML with ``highlight-email`` wrapper classes that the
    stylesheet in ``src/css/app.css`` styles. Returns the original value
    when empty.
    """
    if not value:
        return ""
    return mark_safe(highlight(value, EmailLexer(), _email_formatter))
