"""Webhook dispatch tasks for incoming mail.

Follows the Standard Webhooks specification (standardwebhooks.com) so
clients can use off-the-shelf SDKs for signature verification.
"""

import json
import logging
import time
import uuid

import httpx
from django.conf import settings
from django.tasks import task

from .models import IncomingMessage, Webhook, WebhookDelivery

logger = logging.getLogger(__name__)


@task
def dispatch_webhook(message_id):
    """Deliver an incoming message to all matching active webhooks for its org."""
    message = IncomingMessage.objects.get(pk=message_id)
    webhooks = Webhook.objects.filter(org=message.org, is_active=True)
    any_sent = False

    for webhook in webhooks:
        if not webhook.matches(message.rcpt_to):
            continue
        ok = deliver_to_webhook(message, webhook)
        if ok:
            any_sent = True

    match [any_sent, webhooks.exists()]:
        case [True, _]:
            message.status = IncomingMessage.Status.WEBHOOK_SENT
        case [False, True]:
            message.status = IncomingMessage.Status.WEBHOOK_FAILED
        case _:
            message.status = IncomingMessage.Status.DROPPED
    message.save(update_fields=["status"])


def deliver_to_webhook(message, webhook, is_test=False):
    """POST a Standard Webhooks compliant signed payload. Return ok."""
    msg_id = f"msg_{message.id}" if message else f"msg_{uuid.uuid7()}"
    timestamp = int(time.time())
    payload = build_payload(message, is_test)
    payload_bytes = json.dumps(payload, sort_keys=True).encode()
    signature = webhook.sign(msg_id, timestamp, payload_bytes)

    try:
        response = httpx.post(
            webhook.url,
            content=payload_bytes,
            headers={
                "Content-Type": "application/json",
                "webhook-id": msg_id,
                "webhook-timestamp": str(timestamp),
                "webhook-signature": signature,
            },
            timeout=settings.RELAY_WEBHOOK_TIMEOUT,
        )
        ok = response.is_success
        WebhookDelivery.objects.create(
            message=message,
            webhook=webhook,
            is_test=is_test,
            status=WebhookDelivery.Status.SENT if ok else WebhookDelivery.Status.FAILED,
            response_code=response.status_code,
            response_body=response.text[:2000],
        )
    except Exception as e:
        logger.error(f"Webhook delivery to {webhook.url} failed: {e}")
        WebhookDelivery.objects.create(
            message=message,
            webhook=webhook,
            is_test=is_test,
            status=WebhookDelivery.Status.FAILED,
            response_body=str(e)[:2000],
        )
        ok = False

    return ok


def build_payload(message, is_test=False):
    """Build the webhook payload — flat event data, metadata in headers.

    The ``body_url`` is generated by the storage backend (presigned S3 URL
    in production). The raw body is never included inline.
    """
    return {
        "type": "email.test" if is_test else "email.received",
        "message_id": str(message.id) if message else None,
        "from": message.mail_from if message else "test@relay.example",
        "to": message.rcpt_to if message else "test@example.com",
        "subject": message.subject if message else "Relay webhook test",
        "rfc822_message_id": message.message_id if message else "",
        "received_with_tls": message.received_with_tls if message else False,
        "domain": message.receiving_domain if message else None,
        "body_url": message.raw_body.url if message and message.raw_body else None,
    }
