import gzip
import logging
import uuid

from django.conf import settings
from django.core.mail import EmailMessage
from django.db import models
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from abstract.email_utils import iter_attachments
from abstract.models import TimeStamped
from mx.models import IncomingMessage

from .parser import parse_arf, parse_dmarc_xml

logger = logging.getLogger(__name__)


class DmarcReport(IncomingMessage):
    """Aggregate DMARC report received from a reporting organization."""

    class Disposition(models.TextChoices):
        NONE = "none", _("none")
        QUARANTINE = "quarantine", _("quarantine")
        REJECT = "reject", _("reject")

    domain = models.ForeignKey(
        "domains.Domain",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="dmarc_reports",
        help_text=_("Monitored domain."),
    )
    reporting_org = models.TextField(
        _("reporting organization"),
        blank=True,
        help_text=_("Organization that generated the report (from XML metadata)."),
    )
    reporting_email = models.EmailField(
        _("reporting email"),
        blank=True,
        help_text=_("Contact email from the report metadata."),
    )
    report_id = models.TextField(
        _("report ID"),
        help_text=_("Unique report identifier from the reporting organization."),
    )
    begin_at = models.DateTimeField(
        _("begin at"),
        null=True,
        blank=True,
        help_text=_("Start of the report period."),
    )
    end_at = models.DateTimeField(
        _("end at"),
        null=True,
        blank=True,
        help_text=_("End of the report period."),
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["domain", "report_id"],
                name="unique_dmarc_report",
            ),
        ]
        indexes = [
            models.Index(fields=["begin_at"]),
        ]

    def __str__(self):
        return f"{self.reporting_org} → {self.domain or '?'} ({self.report_id})"

    def get_absolute_url(self):
        return reverse(
            "dmarc:report-detail",
            kwargs={"org_slug": self.org.slug, "pk": self.pk},
        )

    @classmethod
    def parse_from_email(cls, raw_bytes):
        """Return a DmarcReport instance and DmarcRecord list parsed from a raw email.

        Raises `ValueError` if no XML attachment is found.
        """
        data = next(iter_attachments(raw_bytes), None)
        if data is None:
            raise ValueError("No attachment found in DMARC report email.")
        parsed = parse_dmarc_xml(data)
        meta = parsed["metadata"]
        report = cls(
            reporting_org=meta["reporting_org"],
            reporting_email=meta["reporting_email"],
            report_id=meta["report_id"],
            begin_at=meta["begin_at"],
            end_at=meta["end_at"],
        )
        records = [
            DmarcRecord(report=report, **record_data)
            for record_data in parsed["records"]
        ]
        return report, records

    @classmethod
    def send_rua_report(cls, domain, evaluations, begin_at, end_at):
        """Generate and deliver a DMARC aggregate (RUA) report for a domain."""
        report_id = str(uuid.uuid7())
        xml = render_to_string(
            "dmarc/rua_report.xml",
            {
                "reporting_email": f"{settings.RELAY_DMARC_REPORT_LOCAL_PART}@{settings.RELAY_PLATFORM_DOMAIN}",
                "report_id": report_id,
                "begin_timestamp": int(begin_at.timestamp()),
                "end_timestamp": int(end_at.timestamp()),
                "domain_name": domain.name,
                "evaluations": evaluations,
            },
        )
        compressed = gzip.compress(xml.encode("UTF-8"))
        email = EmailMessage(
            subject=f"Report Domain: {domain.name} Submitter: relay Report-ID: {report_id}",
            body="This is a DMARC aggregate report generated by relay.",
            from_email=f"{settings.RELAY_DMARC_REPORT_LOCAL_PART}@{settings.RELAY_PLATFORM_DOMAIN}",
            to=[domain.dmarc_reporting_address],
        )
        email.attach(
            f"{domain.name}!{report_id}!relay.xml.gz", compressed, "application/gzip"
        )
        email.send()


class DmarcRecord(TimeStamped):
    """Source-IP record within a DMARC aggregate report."""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid7,
        editable=False,
    )

    class Alignment(models.TextChoices):
        PASS = "pass", _("pass")
        FAIL = "fail", _("fail")

    class AuthResult(models.TextChoices):
        PASS = "pass", _("pass")
        FAIL = "fail", _("fail")
        NEUTRAL = "neutral", _("neutral")
        NONE = "none", _("none")
        PERMERROR = "permerror", _("permerror")
        TEMPERROR = "temperror", _("temperror")

    report = models.ForeignKey(
        DmarcReport,
        on_delete=models.CASCADE,
        related_name="records",
    )
    source_ip_address = models.GenericIPAddressField(
        _("source IP address"),
        help_text=_("Sending IP address."),
    )
    count = models.PositiveIntegerField(
        _("count"),
        default=0,
        help_text=_("Number of messages from this source IP."),
    )
    disposition = models.TextField(
        _("disposition"),
        choices=DmarcReport.Disposition,
        help_text=_("DMARC policy outcome for this source."),
    )
    dkim_alignment = models.TextField(
        _("DKIM alignment"),
        choices=Alignment,
        help_text=_("DKIM alignment result."),
    )
    spf_alignment = models.TextField(
        _("SPF alignment"),
        choices=Alignment,
        help_text=_("SPF alignment result."),
    )
    header_from = models.TextField(
        _("header from"),
        blank=True,
        help_text=_("From header domain."),
    )
    envelope_from = models.TextField(
        _("envelope from"),
        blank=True,
        help_text=_("Envelope sender domain (MAIL FROM)."),
    )
    dkim_domain = models.TextField(
        _("DKIM domain"),
        blank=True,
        help_text=_("DKIM signing domain."),
    )
    dkim_result = models.TextField(
        _("DKIM result"),
        choices=AuthResult,
        blank=True,
        help_text=_("DKIM authentication result."),
    )
    spf_domain = models.TextField(
        _("SPF domain"),
        blank=True,
        help_text=_("SPF checked domain."),
    )
    spf_result = models.TextField(
        _("SPF result"),
        choices=AuthResult,
        blank=True,
        help_text=_("SPF authentication result."),
    )

    class Meta:
        indexes = [
            models.Index(fields=["report", "source_ip_address"]),
        ]

    def __str__(self):
        return f"{self.source_ip_address} ×{self.count} ({self.disposition})"


class DmarcFailureReport(IncomingMessage):
    """DMARC forensic (RUF) report received from a reporting organization."""

    class DeliveryResult(models.TextChoices):
        DELIVERED = "delivered", _("delivered")
        SPAM = "spam", _("spam")
        POLICY = "policy", _("policy")
        REJECTED = "rejected", _("rejected")
        OTHER = "other", _("other")

    domain = models.ForeignKey(
        "domains.Domain",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="dmarc_failure_reports",
        help_text=_("Monitored domain."),
    )
    reporting_org = models.TextField(
        _("reporting organization"),
        blank=True,
        help_text=_("Organization that generated the report."),
    )
    reporting_email = models.EmailField(
        _("reporting email"),
        blank=True,
        help_text=_("Contact email from the report metadata."),
    )
    source_ip_address = models.GenericIPAddressField(
        _("source IP address"),
        null=True,
        blank=True,
        help_text=_("Sending IP address."),
    )
    arrival_at = models.DateTimeField(
        _("arrival at"),
        null=True,
        blank=True,
        help_text=_("When the original message was received."),
    )
    original_mail_from = models.EmailField(
        _("original mail from"),
        blank=True,
        help_text=_("Envelope sender of the original message."),
    )
    original_rcpt_to = models.EmailField(
        _("original rcpt to"),
        blank=True,
        help_text=_("Envelope recipient of the original message."),
    )
    authentication_results = models.TextField(
        _("authentication results"),
        blank=True,
        help_text=_("SPF and DKIM authentication results from the report."),
    )
    delivery_result = models.TextField(
        _("delivery result"),
        choices=DeliveryResult,
        default=DeliveryResult.OTHER,
        help_text=_("What the reporting MTA did with the message."),
    )
    original_headers = models.TextField(
        _("original headers"),
        blank=True,
        help_text=_("Headers of the original message from the report."),
    )

    class Meta:
        indexes = [
            models.Index(fields=["arrival_at"]),
        ]

    def __str__(self):
        return (
            f"{self.reporting_org} → {self.domain or '?'} ({self.original_mail_from})"
        )

    def get_absolute_url(self):
        return reverse(
            "dmarc:failure-report-detail",
            kwargs={"org_slug": self.org.slug, "pk": self.pk},
        )

    @classmethod
    def parse_from_email(cls, raw_bytes):
        """Return a DmarcFailureReport instance parsed from a raw ARF email.

        Raises `ValueError` if no ARF feedback-report content is found.
        """
        parsed = parse_arf(raw_bytes)
        return cls(
            reporting_org=parsed["reporting_org"],
            reporting_email=parsed["reporting_email"],
            source_ip_address=parsed["source_ip_address"] or None,
            arrival_at=parsed["arrival_at"],
            original_mail_from=parsed["original_mail_from"],
            original_rcpt_to=parsed["original_rcpt_to"],
            authentication_results=parsed["authentication_results"],
            delivery_result=parsed["delivery_result"],
            original_headers=parsed["original_headers"],
        )

    @classmethod
    def send_ruf_report(cls, incoming_message, evaluation):
        """Generate and deliver a DMARC forensic (RUF) report for a failed message."""
        from django.conf import settings
        from django.core.mail import EmailMessage

        from domains.models import Domain

        try:
            domain = Domain.objects.root_for(incoming_message.receiving_domain)
        except Domain.DoesNotExist:
            logger.warning(
                "No domain was found for the RUF report: %s",
                incoming_message.receiving_domain,
            )
        else:
            body = cls.build_arf_body(
                source_ip=evaluation.source_ip_address or "unknown",
                arrival_date=incoming_message.created_at.isoformat(),
                envelope_from=incoming_message.mail_from,
                rcpt_to=incoming_message.rcpt_to,
                auth_results=str(evaluation.dkim_result),
                delivery_result="policy",
                original_headers=incoming_message.raw_body.read().decode(
                    "utf-8", errors="replace"
                )[:2000]
                if incoming_message.raw_body
                else "",
            )
            email = EmailMessage(
                subject=f"DMARC failure report for {domain.name}",
                body=body,
                from_email=f"{settings.RELAY_DMARC_RUF_LOCAL_PART}@{settings.RELAY_PLATFORM_DOMAIN}",
                to=[domain.dmarc_ruf_reporting_address],
            )
            email.send()

    @staticmethod
    def build_arf_body(**fields):
        lines = [
            "This is an email abuse report for an email message received from",
            f"IP {fields.get('source_ip', 'unknown')} on {fields.get('arrival_date', 'unknown')}.",
            "",
            "The message was rejected because it failed DMARC authentication.",
            "",
            "--boundary",
            "Content-Type: text/plain",
            "",
            "DMARC authentication failure report.",
            "",
            "--boundary",
            "Content-Type: message/feedback-report",
            "",
            "Feedback-Type: auth-failure",
            "User-Agent: relay",
            "Version: 1",
            f"Original-Mail-From: {fields.get('envelope_from', '')}",
            f"Original-Rcpt-To: {fields.get('rcpt_to', '')}",
            f"Arrival-Date: {fields.get('arrival_date', '')}",
            f"Source-IP: {fields.get('source_ip', '')}",
            f"Authentication-Results: {fields.get('auth_results', '')}",
            f"Delivery-Result: {fields.get('delivery_result', 'policy')}",
            "",
            "--boundary",
            "Content-Type: text/rfc822-headers",
            "",
            fields.get("original_headers", ""),
            "",
            "--boundary--",
        ]
        return "\n".join(lines)
