"""Generate and send DMARC aggregate (RUA) and forensic (RUF) reports.

Outbound reports are sent as outgoing messages — no database tracking
is needed since the report email itself serves as the record.
"""

import gzip
import logging
import uuid
import xml.etree.ElementTree as ET

from django.conf import settings
from django.core.mail import EmailMessage

logger = logging.getLogger(__name__)


def generate_rua_xml(domain_name, evaluations, begin_at, end_at):
    """Generate a DMARC aggregate report XML string.

    - **domain_name**: the monitored domain.
    - **evaluations**: list of dicts with source_ip_address, disposition,
      dkim_alignment, spf_alignment, header_from, dkim_domain, dkim_result,
      spf_domain, spf_result.
    - **begin_at** / **end_at**: the report period.
    """
    report_id = str(uuid.uuid7())
    root = ET.Element("feedback")

    metadata = ET.SubElement(root, "report_metadata")
    ET.SubElement(metadata, "org_name").text = "relay"
    ET.SubElement(
        metadata, "email"
    ).text = (
        f"{settings.RELAY_DMARC_REPORT_LOCAL_PART}@{settings.RELAY_PLATFORM_DOMAIN}"
    )
    ET.SubElement(metadata, "report_id").text = report_id
    date_range = ET.SubElement(metadata, "date_range")
    ET.SubElement(date_range, "begin").text = str(int(begin_at.timestamp()))
    ET.SubElement(date_range, "end").text = str(int(end_at.timestamp()))

    policy = ET.SubElement(root, "policy_published")
    ET.SubElement(policy, "domain").text = domain_name
    ET.SubElement(policy, "adkim").text = "r"
    ET.SubElement(policy, "aspf").text = "r"
    ET.SubElement(policy, "p").text = "none"
    ET.SubElement(policy, "sp").text = "none"
    ET.SubElement(policy, "pct").text = "100"

    for evaluation in evaluations:
        record = ET.SubElement(root, "record")
        row = ET.SubElement(record, "row")
        ET.SubElement(row, "source_ip").text = evaluation.get("source_ip_address", "")
        ET.SubElement(row, "count").text = "1"
        policy_eval = ET.SubElement(row, "policy_evaluated")
        ET.SubElement(policy_eval, "disposition").text = evaluation.get(
            "disposition", "none"
        )
        ET.SubElement(policy_eval, "dkim").text = evaluation.get(
            "dkim_alignment", "fail"
        )
        ET.SubElement(policy_eval, "spf").text = evaluation.get("spf_alignment", "fail")

        identifiers = ET.SubElement(record, "identifiers")
        ET.SubElement(identifiers, "header_from").text = evaluation.get(
            "header_from", ""
        )

        auth_results = ET.SubElement(record, "auth_results")
        dkim_result = ET.SubElement(auth_results, "dkim")
        ET.SubElement(dkim_result, "domain").text = evaluation.get("dkim_domain", "")
        ET.SubElement(dkim_result, "result").text = evaluation.get(
            "dkim_result", "none"
        )
        spf_result = ET.SubElement(auth_results, "spf")
        ET.SubElement(spf_result, "domain").text = evaluation.get("spf_domain", "")
        ET.SubElement(spf_result, "result").text = evaluation.get("spf_result", "none")

    xml_bytes = ET.tostring(root, encoding="UTF-8", xml_declaration=True)
    return xml_bytes, report_id


def send_rua_report(recipient, domain_name, xml_bytes, report_id):
    """Send a DMARC aggregate report email with gzip-compressed XML attachment."""
    compressed = gzip.compress(xml_bytes)
    email = EmailMessage(
        subject=f"Report Domain: {domain_name} Submitter: relay Report-ID: {report_id}",
        body="This is a DMARC aggregate report generated by relay.",
        from_email=f"{settings.RELAY_DMARC_REPORT_LOCAL_PART}@{settings.RELAY_PLATFORM_DOMAIN}",
        to=[recipient],
    )
    filename = f"{domain_name}!{report_id}!relay.xml.gz"
    email.attach(filename, compressed, "application/gzip")
    email.send()


def extract_rua_address(rua_value):
    """Extract the first mailto: address from a DMARC rua/ruf tag value."""
    if not rua_value:
        return ""
    for part in rua_value.split(","):
        part = part.strip()
        if part.startswith("mailto:"):
            return part.removeprefix("mailto:").strip()
    return ""


def build_arf_report(**fields):
    """Build an ARF (Abuse Reporting Format) report body."""
    lines = [
        "This is an email abuse report for an email message received from",
        f"IP {fields.get('source_ip', 'unknown')} on {fields.get('arrival_date', 'unknown')}.",
        "",
        "The message was rejected because it failed DMARC authentication.",
        "",
        "--boundary",
        "Content-Type: text/plain",
        "",
        "DMARC authentication failure report.",
        "",
        "--boundary",
        "Content-Type: message/feedback-report",
        "",
        "Feedback-Type: auth-failure",
        "User-Agent: relay",
        "Version: 1",
        f"Original-Mail-From: {fields.get('envelope_from', '')}",
        f"Original-Rcpt-To: {fields.get('rcpt_to', '')}",
        f"Arrival-Date: {fields.get('arrival_date', '')}",
        f"Source-IP: {fields.get('source_ip', '')}",
        f"Authentication-Results: {fields.get('auth_results', '')}",
        f"Delivery-Result: {fields.get('delivery_result', 'policy')}",
        "",
        "--boundary",
        "Content-Type: text/rfc822-headers",
        "",
        fields.get("original_headers", ""),
        "",
        "--boundary--",
    ]
    return "\n".join(lines)
