"""Generate and send DMARC aggregate (RUA) and forensic (RUF) reports."""

import gzip
import logging
import uuid

from django.conf import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string

logger = logging.getLogger(__name__)


def generate_rua_xml(domain_name, evaluations, begin_at, end_at):
    """Render a DMARC aggregate report XML string using a Django template.

    - **domain_name**: the monitored domain.
    - **evaluations**: list of dicts with source_ip_address, disposition,
      dkim_alignment, spf_alignment, header_from, dkim_domain, dkim_result,
      spf_domain, spf_result.
    - **begin_at** / **end_at**: the report period.
    """
    report_id = str(uuid.uuid7())
    xml = render_to_string(
        "dmarc/rua_report.xml",
        {
            "reporting_email": (
                f"{settings.RELAY_DMARC_REPORT_LOCAL_PART}"
                f"@{settings.RELAY_PLATFORM_DOMAIN}"
            ),
            "report_id": report_id,
            "begin_timestamp": int(begin_at.timestamp()),
            "end_timestamp": int(end_at.timestamp()),
            "domain_name": domain_name,
            "evaluations": evaluations,
        },
    )
    return xml.encode("UTF-8"), report_id


def send_rua_report(recipient, domain_name, xml_bytes, report_id):
    """Deliver a DMARC aggregate report email with gzip-compressed XML attachment."""
    compressed = gzip.compress(xml_bytes)
    email = EmailMessage(
        subject=f"Report Domain: {domain_name} Submitter: relay Report-ID: {report_id}",
        body="This is a DMARC aggregate report generated by relay.",
        from_email=f"{settings.RELAY_DMARC_REPORT_LOCAL_PART}@{settings.RELAY_PLATFORM_DOMAIN}",
        to=[recipient],
    )
    filename = f"{domain_name}!{report_id}!relay.xml.gz"
    email.attach(filename, compressed, "application/gzip")
    email.send()


def extract_rua_address(rua_value):
    """Return the first mailto: address from a DMARC rua/ruf tag value."""
    if not rua_value:
        return ""
    for part in rua_value.split(","):
        part = part.strip()
        if part.startswith("mailto:"):
            return part.removeprefix("mailto:").strip()
    return ""


def build_arf_report(**fields):
    """Return an ARF (Abuse Reporting Format) report body as a string."""
    lines = [
        "This is an email abuse report for an email message received from",
        f"IP {fields.get('source_ip', 'unknown')} on {fields.get('arrival_date', 'unknown')}.",
        "",
        "The message was rejected because it failed DMARC authentication.",
        "",
        "--boundary",
        "Content-Type: text/plain",
        "",
        "DMARC authentication failure report.",
        "",
        "--boundary",
        "Content-Type: message/feedback-report",
        "",
        "Feedback-Type: auth-failure",
        "User-Agent: relay",
        "Version: 1",
        f"Original-Mail-From: {fields.get('envelope_from', '')}",
        f"Original-Rcpt-To: {fields.get('rcpt_to', '')}",
        f"Arrival-Date: {fields.get('arrival_date', '')}",
        f"Source-IP: {fields.get('source_ip', '')}",
        f"Authentication-Results: {fields.get('auth_results', '')}",
        f"Delivery-Result: {fields.get('delivery_result', 'policy')}",
        "",
        "--boundary",
        "Content-Type: text/rfc822-headers",
        "",
        fields.get("original_headers", ""),
        "",
        "--boundary--",
    ]
    return "\n".join(lines)
