# Generated by Django 6.0.6 on 2026-07-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("domains", "0001_initial"),
        ("mx", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DmarcReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "reporting_org",
                    models.CharField(
                        blank=True,
                        help_text="Organization that generated the report (from XML metadata).",
                        max_length=255,
                        verbose_name="reporting organization",
                    ),
                ),
                (
                    "reporting_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email from the report metadata.",
                        max_length=254,
                        verbose_name="reporting email",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        help_text="Unique report identifier from the reporting organization.",
                        max_length=255,
                        verbose_name="report ID",
                    ),
                ),
                (
                    "begin_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the report period.",
                        null=True,
                        verbose_name="begin at",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the report period.",
                        null=True,
                        verbose_name="end at",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("parsed", "parsed"),
                            ("failed", "failed"),
                        ],
                        default="received",
                        help_text="Report processing lifecycle state.",
                        max_length=8,
                        verbose_name="status",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Parse error detail if processing failed.",
                        verbose_name="error",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Monitored domain.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dmarc_reports",
                        to="domains.domain",
                    ),
                ),
                (
                    "incoming_message",
                    models.OneToOneField(
                        help_text="Incoming email that delivered this report.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dmarc_report",
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dmarc_reports",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DmarcRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "source_ip_address",
                    models.GenericIPAddressField(
                        help_text="Sending IP address.",
                        verbose_name="source IP address",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of messages from this source IP.",
                        verbose_name="count",
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("quarantine", "quarantine"),
                            ("reject", "reject"),
                        ],
                        help_text="DMARC policy outcome for this source.",
                        max_length=10,
                        verbose_name="disposition",
                    ),
                ),
                (
                    "dkim_alignment",
                    models.CharField(
                        choices=[("pass", "pass"), ("fail", "fail")],
                        help_text="DKIM alignment result.",
                        max_length=4,
                        verbose_name="DKIM alignment",
                    ),
                ),
                (
                    "spf_alignment",
                    models.CharField(
                        choices=[("pass", "pass"), ("fail", "fail")],
                        help_text="SPF alignment result.",
                        max_length=4,
                        verbose_name="SPF alignment",
                    ),
                ),
                (
                    "header_from",
                    models.CharField(
                        blank=True,
                        help_text="From header domain.",
                        max_length=255,
                        verbose_name="header from",
                    ),
                ),
                (
                    "envelope_from",
                    models.CharField(
                        blank=True,
                        help_text="Envelope sender domain (MAIL FROM).",
                        max_length=255,
                        verbose_name="envelope from",
                    ),
                ),
                (
                    "dkim_domain",
                    models.CharField(
                        blank=True,
                        help_text="DKIM signing domain.",
                        max_length=255,
                        verbose_name="DKIM domain",
                    ),
                ),
                (
                    "dkim_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "pass"),
                            ("fail", "fail"),
                            ("neutral", "neutral"),
                            ("none", "none"),
                            ("permerror", "permerror"),
                            ("temperror", "temperror"),
                        ],
                        help_text="DKIM authentication result.",
                        max_length=9,
                        verbose_name="DKIM result",
                    ),
                ),
                (
                    "spf_domain",
                    models.CharField(
                        blank=True,
                        help_text="SPF checked domain.",
                        max_length=255,
                        verbose_name="SPF domain",
                    ),
                ),
                (
                    "spf_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "pass"),
                            ("fail", "fail"),
                            ("neutral", "neutral"),
                            ("none", "none"),
                            ("permerror", "permerror"),
                            ("temperror", "temperror"),
                        ],
                        help_text="SPF authentication result.",
                        max_length=9,
                        verbose_name="SPF result",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="dmarc.dmarcreport",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutgoingDmarcReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("rua", "RUA"), ("ruf", "RUF")],
                        default="rua",
                        help_text="RUA (aggregate) or RUF (forensic).",
                        max_length=3,
                        verbose_name="report type",
                    ),
                ),
                (
                    "recipient",
                    models.EmailField(
                        help_text="Email address the report was sent to.",
                        max_length=254,
                        verbose_name="recipient",
                    ),
                ),
                (
                    "begin_at",
                    models.DateTimeField(
                        help_text="Start of the report period.", verbose_name="begin at"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        help_text="End of the report period.", verbose_name="end at"
                    ),
                ),
                (
                    "record_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of records included in the report.",
                        verbose_name="record count",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "generating"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                        ],
                        default="generating",
                        help_text="Report sending lifecycle state.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Error detail if sending failed.",
                        verbose_name="error",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Domain the report covers.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_dmarc_reports",
                        to="domains.domain",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_dmarc_reports",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DmarcEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "source_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Sending IP address.",
                        null=True,
                        verbose_name="source IP address",
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("quarantine", "quarantine"),
                            ("reject", "reject"),
                        ],
                        default="none",
                        help_text="DMARC policy outcome.",
                        max_length=10,
                        verbose_name="disposition",
                    ),
                ),
                (
                    "dkim_alignment",
                    models.CharField(
                        choices=[("pass", "pass"), ("fail", "fail")],
                        default="fail",
                        help_text="DKIM alignment result.",
                        max_length=4,
                        verbose_name="DKIM alignment",
                    ),
                ),
                (
                    "spf_alignment",
                    models.CharField(
                        choices=[("pass", "pass"), ("fail", "fail")],
                        default="fail",
                        help_text="SPF alignment result.",
                        max_length=4,
                        verbose_name="SPF alignment",
                    ),
                ),
                (
                    "header_from",
                    models.CharField(
                        blank=True,
                        help_text="From header domain.",
                        max_length=255,
                        verbose_name="header from",
                    ),
                ),
                (
                    "envelope_from",
                    models.CharField(
                        blank=True,
                        help_text="Envelope sender domain (MAIL FROM).",
                        max_length=255,
                        verbose_name="envelope from",
                    ),
                ),
                (
                    "dkim_domain",
                    models.CharField(
                        blank=True,
                        help_text="DKIM signing domain.",
                        max_length=255,
                        verbose_name="DKIM domain",
                    ),
                ),
                (
                    "dkim_result",
                    models.CharField(
                        choices=[
                            ("pass", "pass"),
                            ("fail", "fail"),
                            ("neutral", "neutral"),
                            ("none", "none"),
                            ("permerror", "permerror"),
                            ("temperror", "temperror"),
                        ],
                        default="none",
                        help_text="DKIM authentication result.",
                        max_length=9,
                        verbose_name="DKIM result",
                    ),
                ),
                (
                    "spf_domain",
                    models.CharField(
                        blank=True,
                        help_text="SPF checked domain.",
                        max_length=255,
                        verbose_name="SPF domain",
                    ),
                ),
                (
                    "spf_result",
                    models.CharField(
                        choices=[
                            ("pass", "pass"),
                            ("fail", "fail"),
                            ("neutral", "neutral"),
                            ("none", "none"),
                            ("permerror", "permerror"),
                            ("temperror", "temperror"),
                        ],
                        default="none",
                        help_text="SPF authentication result.",
                        max_length=9,
                        verbose_name="SPF result",
                    ),
                ),
                (
                    "included_in_report",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this evaluation has been included in a sent report.",
                        verbose_name="included in report",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Domain being evaluated (header-from domain).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dmarc_evaluations",
                        to="domains.domain",
                    ),
                ),
                (
                    "incoming_message",
                    models.OneToOneField(
                        help_text="Incoming message that was evaluated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dmarc_evaluation",
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dmarc_evaluations",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["domain", "included_in_report"],
                        name="dmarc_dmarc_domain__b3927e_idx",
                    ),
                    models.Index(
                        fields=["org", "disposition"],
                        name="dmarc_dmarc_org_id_e7deee_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DmarcFailureReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "reporting_org",
                    models.CharField(
                        blank=True,
                        help_text="Organization that generated the report.",
                        max_length=255,
                        verbose_name="reporting organization",
                    ),
                ),
                (
                    "reporting_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email from the report metadata.",
                        max_length=254,
                        verbose_name="reporting email",
                    ),
                ),
                (
                    "source_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Sending IP address.",
                        null=True,
                        verbose_name="source IP address",
                    ),
                ),
                (
                    "arrival_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the original message was received.",
                        null=True,
                        verbose_name="arrival at",
                    ),
                ),
                (
                    "original_mail_from",
                    models.EmailField(
                        blank=True,
                        help_text="Envelope sender of the original message.",
                        max_length=254,
                        verbose_name="original mail from",
                    ),
                ),
                (
                    "original_rcpt_to",
                    models.EmailField(
                        blank=True,
                        help_text="Envelope recipient of the original message.",
                        max_length=254,
                        verbose_name="original rcpt to",
                    ),
                ),
                (
                    "authentication_results",
                    models.TextField(
                        blank=True,
                        help_text="SPF and DKIM authentication results from the report.",
                        verbose_name="authentication results",
                    ),
                ),
                (
                    "delivery_result",
                    models.CharField(
                        choices=[
                            ("delivered", "delivered"),
                            ("spam", "spam"),
                            ("policy", "policy"),
                            ("rejected", "rejected"),
                            ("other", "other"),
                        ],
                        default="other",
                        help_text="What the reporting MTA did with the message.",
                        max_length=9,
                        verbose_name="delivery result",
                    ),
                ),
                (
                    "original_headers",
                    models.TextField(
                        blank=True,
                        help_text="Headers of the original message from the report.",
                        verbose_name="original headers",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("parsed", "parsed"),
                            ("failed", "failed"),
                        ],
                        default="received",
                        help_text="Report processing lifecycle state.",
                        max_length=8,
                        verbose_name="status",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Parse error detail if processing failed.",
                        verbose_name="error",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Monitored domain.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dmarc_failure_reports",
                        to="domains.domain",
                    ),
                ),
                (
                    "incoming_message",
                    models.OneToOneField(
                        help_text="Incoming email that delivered this report.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dmarc_failure_report",
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dmarc_failure_reports",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["org", "status"], name="dmarc_dmarc_org_id_676db2_idx"
                    ),
                    models.Index(
                        fields=["org", "arrival_at"],
                        name="dmarc_dmarc_org_id_a6d500_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dmarcreport",
            index=models.Index(
                fields=["org", "status"], name="dmarc_dmarc_org_id_e2c61e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dmarcreport",
            index=models.Index(
                fields=["org", "begin_at"], name="dmarc_dmarc_org_id_f8ed52_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dmarcreport",
            constraint=models.UniqueConstraint(
                fields=("domain", "report_id"), name="unique_dmarc_report"
            ),
        ),
        migrations.AddIndex(
            model_name="dmarcrecord",
            index=models.Index(
                fields=["report", "source_ip_address"],
                name="dmarc_dmarc_report__5eff9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outgoingdmarcreport",
            index=models.Index(
                fields=["org", "status"], name="dmarc_outgo_org_id_798329_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outgoingdmarcreport",
            index=models.Index(
                fields=["domain", "report_type"], name="dmarc_outgo_domain__8a0196_idx"
            ),
        ),
    ]
