# Generated by Django 6.0.6 on 2026-07-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("domains", "0001_initial"),
        ("mx", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DmarcReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "reporting_org",
                    models.CharField(
                        blank=True,
                        help_text="Organization that generated the report (from XML metadata).",
                        max_length=255,
                        verbose_name="reporting organization",
                    ),
                ),
                (
                    "reporting_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email from the report metadata.",
                        max_length=254,
                        verbose_name="reporting email",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        help_text="Unique report identifier from the reporting organization.",
                        max_length=255,
                        verbose_name="report ID",
                    ),
                ),
                (
                    "begin_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the report period.",
                        null=True,
                        verbose_name="begin at",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the report period.",
                        null=True,
                        verbose_name="end at",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("parsed", "parsed"),
                            ("failed", "failed"),
                        ],
                        default="received",
                        help_text="Report processing lifecycle state.",
                        max_length=8,
                        verbose_name="status",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Parse error detail if processing failed.",
                        verbose_name="error",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Monitored domain.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dmarc_reports",
                        to="domains.domain",
                    ),
                ),
                (
                    "incoming_message",
                    models.OneToOneField(
                        help_text="Incoming email that delivered this report.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dmarc_report",
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dmarc_reports",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DmarcRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "source_ip_address",
                    models.GenericIPAddressField(
                        help_text="Sending IP address.",
                        verbose_name="source IP address",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of messages from this source IP.",
                        verbose_name="count",
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("quarantine", "quarantine"),
                            ("reject", "reject"),
                        ],
                        help_text="DMARC policy outcome for this source.",
                        max_length=10,
                        verbose_name="disposition",
                    ),
                ),
                (
                    "dkim_alignment",
                    models.CharField(
                        choices=[("pass", "pass"), ("fail", "fail")],
                        help_text="DKIM alignment result.",
                        max_length=4,
                        verbose_name="DKIM alignment",
                    ),
                ),
                (
                    "spf_alignment",
                    models.CharField(
                        choices=[("pass", "pass"), ("fail", "fail")],
                        help_text="SPF alignment result.",
                        max_length=4,
                        verbose_name="SPF alignment",
                    ),
                ),
                (
                    "header_from",
                    models.CharField(
                        blank=True,
                        help_text="From header domain.",
                        max_length=255,
                        verbose_name="header from",
                    ),
                ),
                (
                    "envelope_from",
                    models.CharField(
                        blank=True,
                        help_text="Envelope sender domain (MAIL FROM).",
                        max_length=255,
                        verbose_name="envelope from",
                    ),
                ),
                (
                    "dkim_domain",
                    models.CharField(
                        blank=True,
                        help_text="DKIM signing domain.",
                        max_length=255,
                        verbose_name="DKIM domain",
                    ),
                ),
                (
                    "dkim_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "pass"),
                            ("fail", "fail"),
                            ("neutral", "neutral"),
                            ("none", "none"),
                            ("permerror", "permerror"),
                            ("temperror", "temperror"),
                        ],
                        help_text="DKIM authentication result.",
                        max_length=9,
                        verbose_name="DKIM result",
                    ),
                ),
                (
                    "spf_domain",
                    models.CharField(
                        blank=True,
                        help_text="SPF checked domain.",
                        max_length=255,
                        verbose_name="SPF domain",
                    ),
                ),
                (
                    "spf_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "pass"),
                            ("fail", "fail"),
                            ("neutral", "neutral"),
                            ("none", "none"),
                            ("permerror", "permerror"),
                            ("temperror", "temperror"),
                        ],
                        help_text="SPF authentication result.",
                        max_length=9,
                        verbose_name="SPF result",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="dmarc.dmarcreport",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TlsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "reporting_org",
                    models.CharField(
                        blank=True,
                        help_text="Organization that generated the report.",
                        max_length=255,
                        verbose_name="reporting organization",
                    ),
                ),
                (
                    "reporting_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email from the report metadata.",
                        max_length=254,
                        verbose_name="reporting email",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        help_text="Unique report identifier.",
                        max_length=255,
                        verbose_name="report ID",
                    ),
                ),
                (
                    "begin_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the report period.",
                        null=True,
                        verbose_name="begin at",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the report period.",
                        null=True,
                        verbose_name="end at",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("parsed", "parsed"),
                            ("failed", "failed"),
                        ],
                        default="received",
                        help_text="Report processing lifecycle state.",
                        max_length=8,
                        verbose_name="status",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Parse error detail if processing failed.",
                        verbose_name="error",
                    ),
                ),
                (
                    "successful_session_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total successful TLS sessions.",
                        verbose_name="successful session count",
                    ),
                ),
                (
                    "failed_session_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total failed TLS sessions.",
                        verbose_name="failed session count",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Domain the report covers.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tls_reports",
                        to="domains.domain",
                    ),
                ),
                (
                    "incoming_message",
                    models.OneToOneField(
                        help_text="Incoming email that delivered this report.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tls_report",
                        to="mx.incomingmessage",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Owning organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tls_reports",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TlsFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[("sts", "STS"), ("tlsa", "TLSA")],
                        help_text="Policy that was applied.",
                        max_length=4,
                        verbose_name="policy type",
                    ),
                ),
                (
                    "policy_domain",
                    models.CharField(
                        blank=True,
                        help_text="Domain the policy applies to.",
                        max_length=255,
                        verbose_name="policy domain",
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("starttls-not-supported", "STARTTLS not supported"),
                            ("certificate-expired", "certificate expired"),
                            ("certificate-not-trusted", "certificate not trusted"),
                            ("certificate-name-mismatch", "certificate name mismatch"),
                            ("tls-version-invalid", "TLS version invalid"),
                            ("tlsa-invalid", "TLSA invalid"),
                            ("dane-required", "DANE required"),
                            ("sts-policy-invalid", "STS policy invalid"),
                            ("sts-webpki-invalid", "STS WebPKI invalid"),
                            ("other", "other"),
                        ],
                        help_text="TLS failure type.",
                        max_length=28,
                        verbose_name="result type",
                    ),
                ),
                (
                    "sending_mta_ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address of the sending MTA.",
                        verbose_name="sending MTA IP address",
                    ),
                ),
                (
                    "receiving_mx_hostname",
                    models.CharField(
                        blank=True,
                        help_text="Hostname of the receiving MX.",
                        max_length=255,
                        verbose_name="receiving MX hostname",
                    ),
                ),
                (
                    "receiving_mx_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the receiving MX.",
                        null=True,
                        verbose_name="receiving MX IP address",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of failed sessions with this configuration.",
                        verbose_name="count",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        help_text="Extra failure details from the report.",
                        verbose_name="additional info",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="dmarc.tlsreport",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="dmarcreport",
            index=models.Index(
                fields=["org", "status"], name="dmarc_dmarc_org_id_e2c61e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dmarcreport",
            index=models.Index(
                fields=["org", "begin_at"], name="dmarc_dmarc_org_id_f8ed52_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dmarcreport",
            constraint=models.UniqueConstraint(
                fields=("domain", "report_id"), name="unique_dmarc_report"
            ),
        ),
        migrations.AddIndex(
            model_name="dmarcrecord",
            index=models.Index(
                fields=["report", "source_ip_address"],
                name="dmarc_dmarc_report__5eff9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tlsreport",
            index=models.Index(
                fields=["org", "status"], name="dmarc_tlsre_org_id_6bccc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tlsreport",
            index=models.Index(
                fields=["org", "begin_at"], name="dmarc_tlsre_org_id_3515b1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tlsreport",
            constraint=models.UniqueConstraint(
                fields=("domain", "report_id"), name="unique_tls_report"
            ),
        ),
        migrations.AddIndex(
            model_name="tlsfailure",
            index=models.Index(
                fields=["report", "result_type"], name="dmarc_tlsfa_report__7f4ad5_idx"
            ),
        ),
    ]
